### ISSUE TITLE
ecn stats would be interesting

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#1]
Given your sample size, and probable proportion of osx/ios users, it should be around 2% of the drop stat.

**Comment by rchac** [comment]
I wasn't sure exactly how to parse the output of **tc -s qdisc show** with regards to ecn_mark so I have pasted the output of the command from the ingress and egress interfaces for you to check out. This was over a 14hr period.
[interfaceIn.txt](https://github.com/rchac/LibreQoS/files/5853011/interfaceIn.txt)
[interfaceOut.txt](https://github.com/rchac/LibreQoS/files/5853012/interfaceOut.txt)
I am not sure whether to enable ECN on our LibreQoS instance via sysctl to increase ecn utilization. Would you recommend it?

**Comment by rchac** [comment]
Our server had a hiccup today related to a faulty NIC but I will provide some better ECN stats tomorrow.

**Comment by rchac** [comment]
Hey Dave. Forgive my ignorance - how would I calculate this? Ecn_mark/dropped? Attached are the results of tc -s qdisc show for the inbound and outbound interface.
[interfaceIn.txt](https://github.com/rchac/LibreQoS/files/5859509/interfaceIn.txt)
[interfaceOut.txt](https://github.com/rchac/LibreQoS/files/5859510/interfaceOut.txt)

**Comment by dtaht** [comment]
Ya know it's been so long I don't remember if ecn marks are counted in the drop stats or not in fq_codel. I'll go look it up.

Good to see some marks there, regardless. Those stats from a live system to an end user?

**Comment by dtaht** [comment]
We've discussed this multiple other places, and it's getting better, and closing without a milestone.
