### ISSUE TITLE
Can we use PCQ queue inside HTB ?

### ISSUE THREAD

**Issue by marsalans** [LibreQoE/LibreQoS#107]
I just though if we can create pcq queue inside htb ?

Instead of creating seperate queue for every entry is csv file can we create a single pcq queue in each htb ?

The idea is to categorized like wise service plans. Create another column for service plan tag, 

Circuit ID,Circuit Name,Device ID,Device Name,Parent Node,MAC,IPv4,IPv6,Download Min,Upload Min,Download Max,Upload Max,Comment, Service Plan Tag

,"968 Circle St., Gurnee, IL 60031",1,Device 1,AP_A,,"100.64.0.1, 100.64.0.14",,25,25,155,20,,25U25D
,"31 Marconi Street, Lake In The Hills, IL 60156",2,Device 2,AP_A,,100.64.0.2,,25,25,105,18,,25U25D
,"255 NW. Newport Ave., Jamestown, NY 14701",3,Device 3,AP_9,,100.64.0.3,,5,5,105,18,,5U5D
,"8493 Campfire Street, Peabody, MA 01960",4,Device 4,AP_9,,100.64.0.4,,10,10,105,18,,10U10D
2794,"6 Littleton Drive, Ringgold, GA 30736",5,Device 5,AP_11,,100.64.0.5,,25,5,105,18,,25D5U
2794,"6 Littleton Drive, Ringgold, GA 30736",6,Device 6,AP_11,,100.64.0.6,,5,50,105,18,,5D50U
,"93 Oklahoma Ave., Parsippany, NJ 07054",7,Device 7,AP_1,,100.64.0.7,,100,50,155,20,,100D50U
,"74 Bishop Ave., Bakersfield, CA 93306",8,Device 8,AP_1,,100.64.0.8,,25,5,105,18,,25D5U
,"9598 Peg Shop Drive, Lutherville Timonium, MD 21093",9,Device 9,AP_7,,100.64.0.9,,25,5,105,18,,25D5U
,"115 Gartner Rd., Gettysburg, PA 17325",10,Device 10,AP_7,,100.64.0.10,,25,5,105,18,,25D5U
,"525 Birchpond St., Romulus, MI 48174",11,Device 11,Site_1,,100.64.0.11,,25,5,105,18,,25D5U

like this and mark the IP and use that ip mark in tc rules, option one is to create same pcq queue on every site so load can be balance regardless of parent node or option two to create pcq as required or option 3 use both way

If we are doing CPU binding for queue so can we bind all the cpu cores ?

**Comment by interduo** [comment]
Service Plan Tag ? Why You dont use CircuitID?

**Comment by interduo** [comment]
What adventage gives You HTB+PCQ over HTB+cake?

PCQ? I understand this as alternative for SFQ. This is mainly used for making balances between customer flows.
(In the end the effect for that is if customer is downloading a file on the other device after his router it could use voip other flows with good latency. SFQ works very good with HFSC - we've used it before LibreQoS for 8y+)

**Comment by marsalans** [comment]
> What adventage gives You HTB+PCQ over HTB+cake?
> 
> PCQ? I understand this as alternative for SFQ. This is mainly used for making balances between customer flows. (In the end the effect for that is if customer is downloading a file on the other device after his router it could use voip other flows with good latency. SFQ works very good with HFSC - we've used it before LibreQoS for 8y+)

We can use marked packets with PCQ. and all the cpu use for same service plan.

**Comment by interduo** [comment]
What effect in the end You are awaiting?
Are You are willing to drop using xdp-cpumap-tc?

**Comment by marsalans** [comment]
In Circuit ID, it uses same bucket of bandwidth whether its one IP or multiple. In Service Plan Tag each IP can get full bucket for each of them just like in hqos

**Comment by interduo** [comment]
Do You use v1.2 ?

> In Circuit ID, it uses same bucket of bandwidth whether its one IP or multiple.

```
1000,"968 Circle St., Gurnee, IL 60031",1,Device 1,AP_A,,"100.64.0.1, 100.64.0.14",,25,25,155,20,,25U25D
1000,"31 Marconi Street, Lake In The Hills, IL 60156",2,Device 2,AP_A,,100.64.0.2,,25,25,105,18,,25U25D
```
The CircuitID 1000 will have one bucket with 25,25,155,20 rates.

> In Service Plan Tag each IP can get full bucket for each of them just like in hqos

```
,"968 Circle St., Gurnee, IL 60031",1,Device 1,AP_A,,"100.64.0.1, 100.64.0.14",,25,25,155,20,,25U25D
,"31 Marconi Street, Lake In The Hills, IL 60156",2,Device 2,AP_A,,100.64.0.2,,25,25,105,18,,25U25D
```
Created Circuits will have two buckets with 25,25,155,20 and 25,25,105,18 rates.


@marsalans could You show me an example: part of ShapedDevices.csv, tc commands You want to generate by LibreQoS?
I don't get Your point are what You trying to limit or what is the problem You are trying to resolve.

**Comment by dtaht** [comment]
@marsalans - is this still an issue now that we have /X support? Do we need to care in v1.3?

**Comment by rchac** [comment]
Closed as stale. But if still needed please reopen.
