### ISSUE TITLE
TCP/WAN Accelleration add on?

### ISSUE THREAD

**Issue by syadnom** [LibreQoE/LibreQoS#131]
It would be very interesting to add in some TCP accelleration to the platform as well.  This is something Cambium/Bequant are leaning really really heavily on.   Especially with streaming that is excessively chatty with most services using TCP.  

I kinda mocked this up on a preseem box but ran out of time for these many hobbies.  Something like adding a dual port NIC that supports dpdk and using this project (https://github.com/tcp-acceleration-service/tas) and literally looping that in to the other nic (In NIC 1:1, out NIC 1:2, Back in NIC 2:1 for preseem, out NIC 2:2 to the network.

**Comment by syadnom** [comment]
I don't believe Paraqum is doing TCP accelleration actually.  It's oen of Cambium's arguments to why they are better than PQ...

**Comment by syadnom** [comment]
In it's simplest form, TCP accell is just a caching tcp/ack proxy that responsed to acks on the WAN side.  ie, you get a packet for a customer, you reply to the ack right away on behalf of the customer and then wait for the client to ack, if they don't ack you resend packet.  That destroys the TCP congestion control throttle and often keeps customer speeds low for 'no apparent reason'.  Put it on customer side of the shaper to get downloads accellerated properly.  cake will then essentially dictate the entire congestion control model because you take your whole network worth of links and routers etc out of the mix.

**Comment by thebracket** [comment]
I'm quite enjoying trying to read their code (comments are nice, guys). I see the ack proxy, but it looks like they also do packet combining and their own scheduling queues. It's pretty complicated stuff. (The combining packets thing looks quite scary; try to stuff subsequent packets together - fixing the checksum and timestamps on the way - until you hit the overall MSS and send as a single large TCP packet. That would definitely improve speed, but I wonder how many implementations break because they expected separation?)

There also seems to be some code to play with TCP windows, but I'm struggling to see exactly what it does.

It also looks like it would be tough to fit into XDP (the preferred replacement to DPDK), since it can actually emit or delay packets rather than just inspecting/modifying them.

**Comment by syadnom** [comment]
Well, 'software' isn't even aware of TCP so as long as it doesn't break the computer/devices TCP stack then it really shouldn't be able to cause grief so long as it's doing it without errors.

I'm not sure that's what does the heavy lifting though.  Especially on wireless networks where there's already a lot of frame aggregation and fragmentation 'on the line' and wisps are already building in the routing resources to handle the smaller packets that you'd typically see.  

I think the ack handling is easily 80% of the benefit.   I don't have any metrics for this but I'm not seeing issues on packet count to customers, it's wireless link retransmits (2.5x latency on that packet) and drops that cause congestion control issues. 

Really, and I think this is an ongoing and ever growing issue, is that habitual speed testers overflow simple buffers and queues and the remote side throttles back.  speedtest.net for example does this.  If you drop n packets via mikrotik firewall you can see some pretty dramatic examples.  drop 1 in 100 and you'll lose 5% of the speed.  5 in 100 and you'll be half speed on that speed test.  

What sucks about being a wisp these days is that I have to be so focused on this synthetic testing as one of my primary delivery goals.  yes, I want cleaner streaming flows because it'll save retransmits on to my edge and smooth things out for customers, but I need an optimized TCP experience because of habitual speed testers and how sensative their http/browser/tcp based tests are to anything and everything.

**Comment by rchac** [comment]
Curious if CAKE's [ack-filter](https://patchwork.ozlabs.org/project/netdev/patch/152650254614.25701.1377066681230937234.stgit@alrua-kau/) option would have any benefit here. 

I think it's worth stepping back to evaluate whether TCP acceleration is really strictly needed, or even that beneficial vs our current model with CAKE diffserv4. My network uses Libre and it's pretty much eliminated all speed test complaints. Speed test results are consistently exactly what clients expect. I just throw an extra 15% on top of their speed plan so they don't see a Netflix stream take off a few Mbps. This can be done with ```bandwidthOverheadFactor = 1.15``` in ispConfig.py. It sets overhead for clients only, they still get limited at the true AP capacity regardless.

**Comment by thebracket** [comment]
Wow, `ack-filter` looks very interesting. The discussion especially. It looks like it will help with very asymmetrical connections (25/5 or similar), and not at all with symmetrical. So maybe try it as a tunable option?

Anecdotally, I've talked to a couple of people who swear Bequant (Cambium licensed the TCP optimization for their QoS box from what I remember) is black magic and makes everything better. So I'm interested mostly to find out what the black magic is!

I did a *very* quick test with adding `ack-filter` to the cake command with a small queue, and it's really hard to tell if it helped or not. Neither latency nor throughput changed by a sufficiently large amount to really tell. I'll try again in a more formalized setup at some point.

**Comment by syadnom** [comment]
thebracket, I did a full demo with cambium and bequant and talked tech.  TCP accelleration *IS* the secret sauce.  Their shapers are actually not that impressive.

As far as your ack test, I think you need to introduce some LAN packet loss or latency spikes to actually see something like that working.

**Comment by syadnom** [comment]
ok, in reading on the ack-filter, it's really just ack deduplication and compression.  It's not going to do anything for lost acks that would cause TCP congestion correction efforts to kick in.  I don't think this negates TCP accelleration at all.  

The goal here, as I interpret, is to help with uploads being the limit on downloads expecially when packets aren't 1500.  for example, to stream netflix at 10Mbps you MUST have about 500kbps upload.  To get 10Mbps downloads on an ookla speed test you MUST have almost 1Mbps.  This is why we get a LOT of new customers coming over because they buffer out on their 10x1 DSL circuit that "should" be able to stream happily if not for the often 300-400Kbps upload capability.  If you're deduping the ACKs then you should be lowering those upload requirements a bit.

This would definitely be something to enable by default on cake for libreqos at least when it's a heavily asymetric rate plan because it's there already and may help a bit, but this isn't doing what bequant or a TCP accellerator does in replying to ACK on the edge.

**Comment by dtaht** [comment]
I have a ton more data on ack-filtering https://blog.cerowrt.org/post/ack_filtering/

It also turns out you can delete acks in symmetric scenarios. 

There are two things that can be done to improve ack-filtering in cake. Presently - see above link - the first flow can grab more bandwidth more rapidly than others (still no harm in that), it would be better if, once ack filtered, cake waited a round, to filter more.

The other thing I keep encouraging folk to do is turn on ecn. Congestion control without losing packets.

There are downsides to that - like ack-filtering as presently designed works less - and you have to have more trust in the e2e protocol actually responds to these marks - and we need packet subwindows -

but a lot of people thing ecn is sexy. I have a nuanced view on it...

**Comment by dtaht** [comment]
ack-filtering - were it hard up against the radio - was the project I had had last year but got subsumed by regressions.

You only need one tcp ack per flow - per txop.

**Comment by dtaht** [comment]
btw, the up/down ratio problem with tcp acks gets MUCH worse with ipv6, so I still support ack-de-depluckation (pun attempt) for, say, the next 8 years. :)

**Comment by dansiemon** [comment]
TCP proxies (aka TCP acceleration) are a bad idea in 2022 [1]. Seeing this pushed by vendors in recent months boggles my mind.

There's so much UDP traffic that is of high value and this is going to increase with QUIC and HTTP3.

A network that can't deliver a good experience for TCP without a proxy certainly doesn't deliver a good experience for the UDP based traffic. Worse, 'optimizing' TCP to handle the loss will make it not share the link fairly with other types of traffic.

[1] - At least for U.S. networks, there may still be some very, very bandwidth and loss constrained networks in other parts of the world but they'll still suffer the same downsides.

**Comment by rchac** [comment]
Coming back to this as we approach v1.4 release. I'm hoping to see if we can make a determination here, or punt this to a future version. My vote is to not implement TCP acceleration.

Points against:
- Could compromise net neutrality somewhat
- Comes at the expense of UDP/QUIC - already at [28% adoption and growing](https://radar.cloudflare.com/adoption-and-usage?range=28d). Diminishing benefits over the coming years.
- We don't have any research on SQM + TCP Acceleration vs SQM alone in terms of end-user impact. I think our approach to SQM probably yields a better end-user experience for most networks than "AI driven" approaches like Bequant - except in cases where there's no way to estimate node/AP capacity (like older 4G networks or something like that). Some sort of head-to-head comparison would be nice.
- With a middle-box managing some aspects of TCP session, some sessions would then break if OSPF routes around LibreQoS on the event of a failure

**Comment by dtaht** [comment]
https://github.com/firecracker-microvm/firecracker/issues/3402

**Comment by dtaht** [comment]
Broken window theory?

**Comment by dtaht** [comment]
I would like us to write an editorial about tcp accelleration being a bad idea in 2023.
