### ISSUE TITLE
changelog tracking

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#135]
Per: https://github.com/rchac/LibreQoS/issues/126

Being able to track when a system change started causing customer support calls would be good, so it can be rolled back.

**Comment by Belyivulk** [comment]
The standard settings are indeed set up as above on our system. The adaptive-rx/tx changes I made were just done in ssh and not persistent (so a reboot would have cleared them).

**Comment by rchac** [comment]
Ah ok gotcha. Thank you for clarifying.
