### ISSUE TITLE
Feature bounties

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#139]
I don't know how to do this on github, I just see "bug bounties". I really liked everyone (eventually) chipping in to get the difficult ipv6 thing done, and while we are motoring along for two (three?) core features in v1.3, it's eating a huge amount of time, for love of the craft. So if we could coax appreciative users to throw in for completing a feature and getting it committed to the world as open source or (my preference) free software, it would be great. It doesn't need to be much, but, every little bit helps.

I got involved in libreqos because robert was so insistent about making some donations to my patreon, that I actually got some, and it's the first time I'd had a "tip", in a long while. I'm really enjoying participating in this burgeoning community, and I'm getting a little bit of consulting business out of it now, and can forsee much more in the future, for all of us.

So... I wish to withdraw my patreon request because y'all are doing all the work! Instead, a good non-profit, aims to distribute 80% of the funds it receives to the people doing the work, and tries to eat only 20% for administrative overhead. So if we could setup an official feature bounty program somehow (via github? patreon? what?) along those lines? Or just vector any donations directly at the core dev involved as we did last time, which is even lower overhead!?

Secondly, people could propose features (and bounties) for v1.4, and we could prioritize at least some stuff that way. 

Now, for a while there, it was nearly impossible to form a 501c3 for software. IRS wouldn't allow it. I have the scars on my back from that, still: https://web.archive.org/web/20160307052626/http://icei.org/ - I think conditions are better for that now, and am looking to put the other bufferbloat.net projects under something more like that, next year sometime, or perhaps as an educational institution, which is more my bag. 

VASTLY simpler is the notion of a public benefit corporation.

And as a nerd, I'd really like a t-shirt, or socks, with libreqos on 'em, with some of that other 20%.

Or something like - "At the end of the game, everyone can have sch_cake".

**Comment by dtaht** [comment]
https://www.youtube.com/watch?v=RSsstXfcRWw song of the morning

**Comment by thebracket** [comment]
It's funny, I started the `xdp-cpumap-tc` stuff because we needed it, and then noticed the bounties. I definitely appreciated all the contributions, thank you. :-) My little one especially says "thank you" for a new outfit and big top-up of the formula and diaper/nappy fund. It's truly staggering how much they eat and poop...

I don't know enough about US corporation law to comment meaningfully about public benefit vs 501c3, or even how liability works for such entities (for the inevitable "we 'fixed' a feature and it turned out to unleash horrors from the deep - it happens)

**Comment by dtaht** [comment]
tee-hee... a skinner box is cheaper than nappies... why did those fade away?

I always wanted to have a kid,  just for experiments like that. :)

**Comment by dtaht** [comment]
I'm like that too. I get so enthralled by the difficulty in solving the problem that I'm eating top ramen for weeks at a time, and when I look up, the rent's due. In fact, I'm rather fond of top ramen, as there's so much you can do with it, if you're creative. Peanut butter can also be used in creative ways. That said... I once thought transactions would be completely frictionless... want some beta eCash from the 90s, cheap? and boy was I wrong. Patreon has grown to be a PITA for me of late, but over time, it's been a big help.

**Comment by rchac** [comment]
> public benefit corporation

I really like this option. As Libre is used by more and more ISPs, having dedicated team of developers would not just propel the project forward, but also allow for its revenue to fund development of upstream projects (XDP, CAKE) and improve the internet as a whole. Mid-sized ISPs are paying tremendous amounts to commercial QoE solutions right now anyway - offering them comparable functionality with an optional support model for larger operators (at a fair price point) seems like the way to go. I insist on keeping the code base FOSS though, with all features remaining in the FOSS project. It's GPLv2 and that can't / should not be changed. I just propose a tier of prompt support for operators where this project is crucial to their operations - and I can handle much of that day-to-day.

> So if we could setup an official feature bounty program somehow (via github? patreon? what?) along those lines? Or just vector any donations directly at the core dev involved as we did last time, which is even lower overhead!?

This could be great too. @thebracket , your work is very crucial here. What would you be comfortable with here? Ideas:
- A public benefit corporation or LLC tied to a patreon. You get shares in the org and pay proportional to software growth.
- I run a patreon and pay you as a contractor and through bug/feature bounties.

I would prefer you get proportionally as the software scales in user base, not just as a contractor (though both are valid).

>And as a nerd, I'd really like a t-shirt, or socks, with libreqos on 'em, with some of that other 20%. Or something like - "At the end of the game, everyone can have sch_cake".

I like this! Merch would be a cool option for a little extra revenue. Patreon support that by the way.

> (for the inevitable "we 'fixed' a feature and it turned out to unleash horrors from the deep - it happens)

Very good point, and a good reason to consider a separate entity from myself (LLC, PBC) accepting any funds. You never know!

**Comment by dtaht** [comment]
I dropped you an email.

**Comment by dtaht** [comment]
Liberapay looks reasonable.

**Comment by dtaht** [comment]
Liberapay looks like a way to get more support from europe.

**Comment by dtaht** [comment]
We have added multiple means of financial support. To not much avail, but it is early days.
