### ISSUE TITLE
IPv6 configuration and testing

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#144]
It would be good to pound 20k unused ipv6 addresses into a production setup and see if that hurts anything.

having at least one production segment of someone's network doing ipv6 through libreqos would also help

rtt measurements between ipv6 vs ipv4 traffic would be interesting on the same customer.

...

There are a zillion ways to configure ipv6 to the premise. I lean towards just assigning a static /56 to each customer and calling it a day. renumbering events for IPv6 are very, very painful. even distributing those /56s via dhcpv6-pd is painful...

However the intermediate hops can be "interesting". There's too much (IMHO) in human friendly ipv6 tunnels (e.g. 2001:db8::2/127 connecting to 2001:db8::3/127, where each router hop if more randomized would be less subject to attack. For a while there, SLAAC seemed to make the most sense (and it still does, for many), but that leaks the underlying MAC and can help fingerprint the OS. Nowadays apple randomizes the mac address. "privacy addresses" are too dynamic. customer_number (or name) sha256'd is what I used to have a useful level of static assignment while preserving some randomness. 

If the intermediate hop is at the customer premise, and doing things like dns, it too needs to be shaped as part of the customer plan.

There are also ways to break out the connection via the single assigned /56, but this breaks a few things, but works in the cell world. Sigh.

**Comment by dtaht** [comment]
Cake does per host/per flow FQ. In the home environment, with the nat option, that would allocate roughly equal bandwidth to every ipv4 device on the customer subnet. In the middlebox world, post nat it reverts to per flow fq, identical to fq_codel except for the diffserv differentiator. IPv6 on the other hand gets us back to per host/per flow fairness e2e. ipv4 post-nat looks like "one host" to cake, so as soon as you add ipv6 to the network devices using it get an automatic boost vs ipv4, which I regard as a good thing. IPv6 + per-host fairness also holds the potential for dramatically improving slow start in particular on our congestion controls, as (for example) a web browser could open up a 100+ connections without fear of overrunning a nat table somewhere, and attempt to download them all at the same time (just shooting the browser user in the foot as for self inflicted congestion). Many devices nowadays have two or more ipv6 addresses and intelligently using those (one for highly interactive traffic) by applications would be a win in these scenarios.

**Comment by rchac** [comment]
IPv6 working great, closed.
