### ISSUE TITLE
anonymity  view  

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#147]
I LOVED (in https://github.com/thebracket/cpumap-pping/issues/2 ) seeing the comparison between the standard and metaverse-ready views, and also... what kind of tool are you using to blur out the sensitive information? It would be very handy to be able to share screen shots like this and automatically have the sensitive data blurred out or replaced with innoculous tags like IP1, IP2, or CUST1, CUST2. 

![](https://user-images.githubusercontent.com/22501920/199216895-9bb57116-228e-4af9-871d-29e4aa679ab6.png)

Similarly in terms of sharing data with a remote tech support person, I really miss the days where we would exchange packet captures, to deeply debug problems. There are a bunch of these tools nowadays - https://www.google.com/search?q=packet+capture+anonymizers

**Comment by rchac** [comment]
Thanks! I just used GIMP and selected a polygon then Filters>Blur>Pixelize. I'll see if there's a way to anonymize the InfluxDB display automatically without changing tags on the backend.

**Comment by thebracket** [comment]
I forgot to tag the relevant commits that add an anonymizing feature (in Klingon). 
https://github.com/LibreQoE/LibreQoS/commit/f79f850079e5c4d3786d73e8e6c1d108a430dc67
https://github.com/LibreQoE/LibreQoS/commit/f5cfd48dd1562f22bc113f39dd3562b25469d21e
https://github.com/LibreQoE/LibreQoS/commit/858ed06286c57f4b3a5314c70e5a1ed03569e173
https://github.com/LibreQoE/LibreQoS/commit/44171d15ea3cb752af4c9b7516ca33eaa72e622e

**Comment by dtaht** [comment]
![image](https://user-images.githubusercontent.com/108682/212147182-4a48fe27-c9bc-4188-b035-ca17c5546c58.png)

Thank you for this. This was the most fun bug/feature request I've made in a long time. I look forward to describing the feature in the release notes, after you close the bug.

**Comment by dtaht** [comment]
I note that this is unfortunately two bugs - in that I'd also wanted a way to anonymize packet captures. We are not in a position to take them anywhere as yet... but we should close this one, do a little victory dance, and think about that other one some other time. Too much less-fun stuff to do.
