### ISSUE TITLE
ack-filtering vs cambium

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#154]
We seemed to have hit a bug with cambium's tcp offload and cake's ack-filtering. Cake's ack-filtering is OF COURSE 100% correct; it must be cambium. Getting a packet trace of what's going wrong there will help both us and them in building better products.

One way to avoid it is to have an exceptions mechanism for cambium paths. I in general think ack-filtering is a win at the cpe itself, and am surprised at how well it works in a middlebox. (so far) And would like it on by default.

**Comment by syadnom** [comment]
Which cambium product in particular?

**Comment by thebracket** [comment]
I tried testing ack-filter (both directions, which was probably a mistake)
on my in-line filter, and had positive reports from everyone except the
people on older Cambium epmp 1k (2.4ghz) systems and a couple of PMP450b
(on Medusa) customers. The last two I'm less certain about. I hope to do
more testing, but not until 1.3 is solid.

**Comment by syadnom** [comment]
I don't have any epmp1k anymore but I used to have VoIP issues across them.  Ended up tunneling out to resolve.  I haven't seen any issues on 450m in 3 ot 5Ghz along those lines though.  Not sure if there's something related between the issues.

**Comment by dtaht** [comment]
My position on ack-filtering is nuanced. Since by doing FQ and AQM, flows are automagically paced and managed well, deleting ACKs will result in bigger bursts from BSD reno transports. It saves on processing at the sender also, to have less acks. It saves an infinitesmal amount of bandwidth. Less acks is easier on forwarding engines also. 

The cake ack-filter is very conservative (aggressive is not) and preserves too many acks, IMHO. 

The first ever downside I've witnessed was hearing that it broke on cambium. 

I was also very interested in the accuracy of the ack-filter with the rtt estimator, and the additional CPU usage, and wanted it on by default in this release, but without testing, I'm totally ready to punt it to v1.4 (or never).

**Comment by dtaht** [comment]
Basically I would support documenting that we've observed some problems with cambium and recommending it be left off on network segments using that, but otherwise encouraging it on.

**Comment by thebracket** [comment]
I added "ack filter" as a gui option in the configurator.

**Comment by dtaht** [comment]
let's document this in the rel notes.
