### ISSUE TITLE
Help Dashboard Influxdb

### ISSUE THREAD

**Issue by sebassur07** [LibreQoE/LibreQoS#157]
help with dashboard

hello I'm trying to test the tool for a project but when uploading the template I get an error.
i already changed the version of InfluxDB but all with the same result.
could you help me please.
![Influxdb](https://user-images.githubusercontent.com/118370736/202211165-a12f8977-f56b-44e3-967b-5b6feab32aa3.png)

**Comment by dtaht** [comment]
Most of the development team is on matrix.org. It might be faster to debug your setup there (if you have an account, I can invite you).

**Comment by sebassur07** [comment]
i don't have an account, can you invite me please

**Comment by dtaht** [comment]
you would need to sign up for an account on something like matrix.org and tell us who you are....

**Comment by sebassur07** [comment]
thank you I am already in matrix.org

**Comment by dtaht** [comment]
[libreqos](https://matrix.to/#/!HPuJeVMGSJchAqJqmN:matrix.org?via=matrix.org)

**Comment by sebassur07** [comment]
it won't let me join it turns out it's invalid
![image](https://user-images.githubusercontent.com/118370736/202233322-39837b71-f84f-48e9-9452-078c5447b3ff.png)

**Comment by dtaht** [comment]
tell me who you are?

**Comment by sebassur07** [comment]
sebassur07

**Comment by dtaht** [comment]
did we fix this for you today? Got any results?
