### ISSUE TITLE
Showing backlog, bandwidth, ack-drops, drops, marks, and delay

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#159]
tc -s qdisc show will show the detailed cake stats, of interesting 

````

                  Tin 0
  thresh          6Mbit
  target          5.0ms
  interval      100.0ms
  pk_delay        781us # peak delay is the peak
  av_delay         38us 
  sp_delay          6us # sparse delay can be mapped to voip


# Persisent backlog is bad

  backlog            0b
  pkts          1372645
  bytes       710494743 

# These are useful to see major ddos traffic

  way_inds        16533
  way_miss         6143
  way_cols            0 # if you see a lot of these you are in trouble.

# 


  drops             247    #  drops
  marks               0 # right now 1% of drops are marks
  ack_drop         1174 # ack drops are 5-10x drops
  sp_flows            0
  bk_flows            1
  un_flows            0
  max_len         14140
  quantum           300


````

basically on an inverse log scale, you can show customer bandwdith at the top, backlog, drops, marks, and ack-drops

**Comment by thebracket** [comment]
You can access the raw stats in JSON format with a button, and we have graphs for backlog, delay, throughput. Each tin separately graphs bytes, drops and marks. We also display memory usage. So that's a pretty good start.

**Comment by dtaht** [comment]
In looking this over again, getting the displays to be more meaningful javascript (colors and whatnot) needs to happen. @richb-hanover is good at graphs, perhaps he could pull the html and look? I started at it, but then wanted to change the format of the results, and ... I'll look at this harder again this week. Wrapping my head around javascript was not as hard as rust but I ended up just drafting what I (as opposed to some operators) wanted to see in the lqtop utility as that was C, not javascript, and then learning more about the bus than I wanted and I'll ... get back on this later after nerdsniping more folk than I already have, like kathie, etc.

**Comment by rchac** [comment]
Just wanted to say it's working great. Great work @thebracket and @dtaht  
![image](https://user-images.githubusercontent.com/22501920/216798120-8ede21e1-05ec-4035-b6ba-a6983ac06521.png)

**Comment by dtaht** [comment]
You will see something far more correct and less smoothed (The decay on the above delay plot hurts me), if you pull, compile, and install my babycake branch. https://github.com/dtaht/sch_cake/tree/babycake - it is a bit involved - you need the kernel headers for your release, make, make install; then completely stop everything, getting rid of every instance of cake running, and rmmod cake.ko, then reinsert it via insmod. After that, all you have to do is track kernel upgrades...

**Comment by rchac** [comment]
Complete in v1.5
