### ISSUE TITLE
WIKI: v1.3 update

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#163]
**this:**
A good choice for this ID would be the subscriber site ID your CRM provides for customer service locations.

**change to this:**
A good choice for this ID would be internet service planid (or the subscriber site ID your CRM provides for customer service locations).

**reason:**
1. Customer could have more than one service in one place.
2. Customers could have one plan for two locations.

**Comment by rchac** [comment]
Implemented
