### ISSUE TITLE
Change "fqOrCodel" param to "sqm"

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#168]
https://github.com/LibreQoE/LibreQoS/blob/main/v1.3/ispConfig.example.py#L5

Here is no description for ack-filter.

@dtaht is it recommended to be set on as default?

**Comment by rchac** [comment]
@interduo ack filter is off by default. It can be enabled with "cake diffserv4 ack-filter" but it is not something we are recommending by default.

**Comment by interduo** [comment]
Thanks for info.

What do You think about changing variable name from "fqOrCodel" - - > "sqm"?

**Comment by rchac** [comment]
That is a good idea. Should we plan this for v1.4? I would change it now but it would break people's ispConfig

**Comment by interduo** [comment]
Yes - always do that kind of things only in unreleased versions.
