### ISSUE TITLE
v1.3 Change - users please add crontab

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#169]
In [this commit](https://github.com/LibreQoE/LibreQoS/commit/1ae0a2d56825b9dc8b48a31a507ce7308848f4dc) we are switching away from the [schedule module](https://github.com/dbader/schedule) - which is a bit too unreliable and occasionally locks up. It is not being maintained for newer versions of python. The main advantage of the schedule module was the ability to schedule events for a particular time of day - in our case - the 4AM reload. Instead, we can use crontab to restart the service at a desired time.

Users - please make sure to add a crontab entry [as described in the wiki](https://github.com/LibreQoE/LibreQoS/wiki/LibreQoS-v1.3-Installation-&-Usage-Guide-Physical-Server-and-Ubuntu-22.04#crontab).

**Comment by dtaht** [comment]
I am not sure if folk will read this, except in the release notes.
