### ISSUE TITLE
Feature request: Shaper-on-a-stick config (XDP on VLAN interfaces)

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#170]
We have had requests to allow for Shaper-on-a-stick configs (XDP on VLAN interfaces) . I don't know if this is even possible with XDP as it stands, but tracking the issue here.

**Comment by interduo** [comment]
I think we do have nearly issue for that:

https://github.com/LibreQoE/LibreQoS/issues/48

**Comment by rchac** [comment]
https://github.com/LibreQoE/LibreQoS/issues/48
