### ISSUE TITLE
refreshBandwidthGraphs

### ISSUE THREAD

**Issue by khandieyea** [LibreQoE/LibreQoS#175]
Hey guys,

Is someone able to elaborate on why we call `refreshBandwidthGraphs` 3 times on scheduler.py?

Thanks :)

```
def graph():
	time.sleep(10)
	try:
		refreshBandwidthGraphs()
	except:
		print("Failed to run refreshBandwidthGraphs()")
	time.sleep(10)
	try:
		refreshBandwidthGraphs()
	except:
		print("Failed to run refreshBandwidthGraphs()")
	time.sleep(10)
	try:
		refreshBandwidthGraphs()
	except:
		print("Failed to run refreshBandwidthGraphs()")
	time.sleep(1)
	try:
		refreshLatencyGraphs()
	except:
		print("Failed to run refreshLatencyGraphs()")
```

**Comment by khandieyea** [comment]
Nvm, I see it now :)

**Comment by rchac** [comment]
The goal is to run bandwidth graphing every 10 seconds and latency graphing every 30-45 seconds. But I should throw the bandwidth part into a for loop to reduce verbosity of the code. Will do shortly.

**Comment by khandieyea** [comment]
I could PR this if its of interest - https://github.com/khandieyea/LibreQoS/blob/main/src/schedulerAdvanced.py

**Comment by rchac** [comment]
@khandieyea That would be great, thank you. I wasn't aware of [apscheduler](https://github.com/agronholm/apscheduler) as an alternative to schedule.

**Comment by khandieyea** [comment]
Cool, will do

**Comment by dtaht** [comment]
@rchac So I am confused, are we using this now?

**Comment by dtaht** [comment]
@khandieyea - got anything else you want to wedge into 1.4?

**Comment by khandieyea** [comment]
> @khandieyea - got anything else you want to wedge into 1.4?

Not at this stage :)

**Comment by dtaht** [comment]
I would like to have a feature freeze no later than feb 7th.
