### ISSUE TITLE
UISP Integration Bug

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#177]
Reported by Trendal on Matrix:

IntegrationUISP.py has an issue, at least with UISP version 1.4.8. The API returns multiple interfaces for each device and some of them have the same IP on them.  integrationUISP.py isn't checking for duplicate IPs.

```                for interface in device["interfaces"]:
                    for ip in interface["addresses"]:
                        ip = ip["cidr"]
                        if isIpv4Permitted(ip):
                            ipv4.append(fixSubnet(ip))
```

could get changed to 

```
                for interface in device["interfaces"]:
                    for ip in interface["addresses"]:
                        ip = ip["cidr"]
                        if isIpv4Permitted(ip):
                            ip = fixSubnet(ip)
                            if ip not in ipv4:
                                ipv4.append(fixSubnet(ip))

```

**Comment by trendal** [comment]
Maybe obvious, but it needs to be fixed in both buildFlatGraph() and buildFullGraph() and the last line ipv4.append(fixSubnet(ip)) can drop the redundant call to fixSubnet()
