### ISSUE TITLE
Is CGNAT inevitable

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#180]
And if so, how do you plan to deploy it? On what kind(s) of hardware?

See also #179

**Comment by dtaht** [comment]
Do we have clear guidelines for dealing with CGNAT or anyone with experience dealing with it?

**Comment by thebracket** [comment]
I think we recommend placing the shaper inside the network, relative to the
NAT box? I hope we do, it's not going to be pleasant if you do it the other
way around!

**Comment by dtaht** [comment]
Thx
