### ISSUE TITLE
Fussy comments on LibreQoS dashboard

### ISSUE THREAD

**Issue by richb-hanover** [LibreQoE/LibreQoS#183]
Dave Täht recently mentioned his copy of LibreQoS at https://payne.taht.net/

My reaction: This is so cool!

But I have a bunch of fussy comments about the Dashboard that could be tweaked over time...

- The LibreQoS icon at upper left could link to libreqos.io - the "Dashboard" item already links back to the current page. (Keep up the Branding and Marketing!)
- The Copyright date at the bottom might have a lighter background so that it's easier to see. Or put it in white text to make it stand out.
- That notice could also list the version of the software currently running.
- In the Configuration:Network page, all the fields are too wide. They expand beyond the white background. All the other tabs (Shaper, Server, etc.) fit the page.

Nice job!

**Comment by richb-hanover** [comment]
More random thoughts:
- It appears the Y axis labels for the "Last 5 Minutes" chart show "10B" when > 10 Gbps are flowing. I would have expected it to be "10G"
- Similarly, when the link is idle, the Y axis is 1 .. 0.5 .. 0, but it's not clear what units. (Maybe "B"?)
- I do see 500k when there's some traffic, so I think I'm understanding the units properly.
- I suspect the X axis on that chart is seconds. But perhaps the zero should be at the right end of the chart, to make it easy to say, "That happened 100 seconds ago."
- Perhaps the X axis could be in "minute quantities" - that is "300 .. 240 .. 180 .. 120 .. 60 .. 0"
- Or should the chart time run left-to-right?
- That X axis could also use a legend of "seconds" somewhere.
- The TCP RTT histogram could use a legend of milliseconds
- The Memory Status pane gets disarranged when the page gets narrow.
   <img width="264" alt="image" src="https://user-images.githubusercontent.com/1094930/211152776-f82d1821-d4c1-4ca5-b9cd-b3a3a48d15a8.png">

All these fussy comments aside, this is a masterful piece of work! Congratulations!

**Comment by thebracket** [comment]
Thank you! 

I agree with all of these! HTML/JS isn't my strongest suit (I'm primarily a back-end sort of developer), so I've tagged these "help wanted" in the hope that someone who is actually good at UI/UX will jump in (it's all in a [development branch](https://github.com/LibreQoE/LibreQoS/tree/v1.4-pre-alpha-rust-integration) right now). In the meantime, I'll see what I can do to improve things.

**Comment by dtaht** [comment]
@richb-hanover I would like to sit with you whilst we address some nagging issues all across the UI, notably with colors. When would you have time?

**Comment by dtaht** [comment]
The memory status thing, on mobile, should just be text, or not displayed at all if we are running at <70% of memory.

**Comment by dtaht** [comment]
Where we're stuck:

* programatically overriding the default color scheme (green up, green down, for shaped
red or a range for bad). Better colors in general. 
* Per-entry color schemes for line graphs (x/y scatter plots)
*  dots for some things rather than lines
* The best way of filling, but not to zero - for when you want to
represent a range, with a value in the middle. It would be really nice
to render a band from (X up to X down, rather than two data sets.
* More compressed json in general and a way to switch between plot types.

**Comment by trendal** [comment]
I'm gonna take a stab at some of this as soon as I can get a dev platform going

**Comment by dtaht** [comment]
Suggestion from NZ: call this "capacity quintile", just circuit utilization, which is what it is...

https://payne.taht.net/circuit_queue?id=7

(I am also not sure this is actually getting calculated correctly at the moment) 

I also kind of wish this was in log scale to see more detail at the lower percentage points.

**Comment by dtaht** [comment]
Herbert has made a few improvements - this shows drops and marks:

![image](https://user-images.githubusercontent.com/108682/226186876-49083dd1-d775-44df-81f6-259a77ab84df.png)

**Comment by dtaht** [comment]
Presently on the main overview page, we are plotting almost exactly the same data 3 different ways. The delays stat is kind of misleading, in that it does not also track the sparse flows stats. 

![image](https://user-images.githubusercontent.com/108682/226187063-2a494546-66aa-4d6f-a71e-16f65afdc742.png)

**Comment by dtaht** [comment]
@richb-hanover - could you take a look with fresh eyes at https://payne.taht.net?

**Comment by richb-hanover** [comment]
Since you ask... Many of my earlier comments remain. I realize they are _cosmetic_, but I think they're important because they give the newcomer a first impression of the fit-and-finish of the rest of the software. 

- There's no need to have two items in the header (the LibreQoS icon and the "Dashboard") link to the home page of the dashboard. Clicking the logo (at top-left) should take you to libreqos.io perhaps in a separate tab. 

- I can't tell what version of LibreQoS is running, That makes it hard to report problems. I still think it would be good to place it next to the copyright notice at the bottom.

- All time chart legends appear to be backwards. The "blasts of data" move to the left on the "Time since now". Zero should be at the right edge of the chart. (However, you _do_ include "seconds" on the axis... Thanks.)

![image](https://user-images.githubusercontent.com/1094930/226211319-54b03986-780e-43bb-b5db-5538878e1178.png)

- The Network settings extends out of the white background
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1094930/226211347-e38ba950-8d86-4450-ac2d-5bfe319f0680.png">

- The popup window showing the available memory gives an unhelpful precision. 64GB (or even 64.9GB) is probably enough.
<img width="199" alt="image" src="https://user-images.githubusercontent.com/1094930/226211367-fb083f5b-ebfd-4251-9234-c414986f6e57.png">

- On this page: https://payne.taht.net/circuit_queue?id=1 the "Queue Funnel" charts keep flickering, or worse, going blank for a couple seconds before re-appearing. (Firefox 111.0 on a Mac)

And congratulations again on this terrific software.

**Comment by dtaht** [comment]
@richb-hanover - we have made a few improvements, but not quite enough, but take a gander at: https://payne.taht.net/ - check out the queue funnel idea and the queue tree view also

I would really like something that looked more like a piano roll.... can't remember the name of the 2002 paper (why do I remember the date, but not the paper) that mapped different flows into a piano roll like graph and their durations....

**Comment by dtaht** [comment]
@richb-hanover need your love

**Comment by richb-hanover** [comment]
@dtaht I'm up to my elbows in stuff this week and next. But I couldn't quickly find the queue funnel or tree view. Could you give me a quick A, B, C to make it dance so I could comment? Thanks.

**Comment by richb-hanover** [comment]
PS I **cannot** easily tell what version of LibreQoS I am looking at. It's a disincentive to report problems, because I can't tell whether I should expect there's anything new (or if it's the same version).

The lack of an obvious version number makes it hard to write bug reports ("I was using payne.taht.net at 12:35pm EDT when I saw this problem...") It's so much easier to copy/paste a version (and build number, if necessary) from the Dashboard. Thanks.
