### ISSUE TITLE
Support reading inside MPLS tags

### ISSUE THREAD

**Issue by thebracket** [LibreQoE/LibreQoS#184]
Extracted from: https://github.com/LibreQoE/LibreQoS/issues/26 - @MrHamel 's comment.

The "tc" dissector can already handle reading MPLS, it needs to be added to the XDP side of the eBPF program.

**Comment by thebracket** [comment]
Very experimental support for reading inside MPLS labels added. It wont like it if you have non-IP as the immediate payload, but it's a good start.

**Comment by MrHamel** [comment]
The MPLS labels are all popped by my Juniper cores before sending the traffic to the edge/peer router, so while it will not be useful for me, I'm sure someone else will and do appreciate the added feature. Thanks!

**Comment by dtaht** [comment]
I would like us to find someone to test this. But let's hope it is right and move on.
