### ISSUE TITLE
UISP integration question

### ISSUE THREAD

**Issue by vettamatt** [LibreQoE/LibreQoS#190]
Hi all!

Firstly, since it's my first message on this project, thank-you to everyone for their work on this project! It's a fantastic asset!

Regarding the UISP integration, I'm ideally wanting the AP's that are added to integrationUISPbandwidths.csv to show in network.json, along with their capacities.

As the UISP I'm working with has UCRM disabled, I'm then intending to get the customer data from a REST API.
That part is fairly straightforward for me.

I'm thinking I should parse through the devices, and for each device, get customer data based upon the mac address and / or IPv4 address, then add the node for the customer, related to the parent AP, then relate the device to the customer.

Does that make sense? Is this functionality already present (and I'm missing the obvious), or should we modify the integration to achieve this?
Happy to modify ourselves, just looking for a logic and sanity check from like-minded people.

**Comment by trendal** [comment]
I'm not much of a contributor (yet, maybe) but I believe there are some significant changes to the UISP integration process coming.  Right now it's missing quit a few of our devices that are not standard CPE -> Tower connections.  I have been intending to poke around and see if I can get some prototype code to pass on to the devs.

**Comment by dtaht** [comment]
@rchac is most into this portion of the codebase. It is often easier and faster  these days to communicate over the #libreqos:matrix.org chat channel to have a conversation like this, if you are up for that?

**Comment by vettamatt** [comment]
> @rchac is most into this portion of the codebase. It is often easier and faster these days to communicate over the #libreqos:matrix.org chat channel to have a conversation like this, if you are up for that?
> 
> I imagine there's no ipv6 here?

Happy to talk on your channel, however I'm seeing that it requires an invite. Any chance of an invite please? @vettamatt:matrix.org

No IPv6 in this case currently, but will happen in the coming year or two probably.

**Comment by dtaht** [comment]
I sent you an invite. We're typically around starting in the wee hours of the morning, starting roughly 6AM PST.

**Comment by rchac** [comment]
> Regarding the UISP integration, I'm ideally wanting the AP's that are added to integrationUISPbandwidths.csv to show in network.json, along with their capacities.

That's how it currently works, assuming you have those APs in UISP and that you set the correct bandwidth rates set in integrationUISPbandwidths.csv. It generates an integrationUISPbandwidths.csv. file with some default rates on the first run of integrationUISP.py.

Just be aware that once integrationUISP.py is run once, and creates your network.json, it won't overwrite it if the file exists. It assumes you might do some customization of network.json and leaves it be after first creation. For example sometimes people need to correct the hierarchy in a way not listed in UISP. So if you want it to be regenerated just delete network.json and then run integrationUISP.py again.

> As the UISP I'm working with has UCRM disabled, I'm then intending to get the customer data from a REST API.
That part is fairly straightforward for me.

>I'm thinking I should parse through the devices, and for each device, get customer data based upon the mac address and / or IPv4 address, then add the node for the customer, related to the parent AP, then relate the device to the customer.

>Does that make sense? Is this functionality already present (and I'm missing the obvious), or should we modify the integration to achieve this?

Interesting. In your particular case, it might be ideal to modify integrationUISP.py (around line 41) to have it pull the client bandwidth rates, perhaps from a custom python script which looks up customer plan rates in your system.

**Comment by dtaht** [comment]
@vettamatt - you got a solution you like here?

**Comment by dtaht** [comment]
@vettamatt nag.

**Comment by mctaguma** [comment]
I've been distracted by other important projects recently, but have made progress.

It would be ideal if the UISP integration could handle devices existing where UCRM is disabled, and still being added to topology, although I understand that is difficult.

I did find a workaround which worked for us, to get those devices into network.json.

**Comment by dtaht** [comment]
@mctaguma are you also @vettamatt  or someone else?

**Comment by vettamatt** [comment]
@dtaht Ha! Yes, same person, @vettamatt at work.
That'll teach me for using the Github mobile app under the wrong account.

**Comment by vettamatt** [comment]
I've fixed the issues I had, with guidance from @rchac, appreciated.
