### ISSUE TITLE
Edit wiki for `python3 -m pip install -r requirements.txt`

### ISSUE THREAD

**Issue by cclauss** [LibreQoE/LibreQoS#191]
Please edit the wiki at https://github.com/LibreQoE/LibreQoS/wiki/LibreQoS-v1.3-Installation-&-Usage-Guide-Physical-Server-and-Ubuntu-22.04#install-libreqos-and-dependencies to use the `python3 -m pip install -r requirements.txt` syntax which was enabled in #189.  If pip-installed dependencies change in the future, we will only need to modify one file.

**Comment by rchac** [comment]
Fixed! Thanks
