### ISSUE TITLE
WIKI Instruction update:

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#195]
There is no turning vlan offload off.

"
If LibreQoS is queueing traffic on many vlans in single interface there should be vlan offload turned off:
 ethtool -K (interface-out) rxvlan off
 ethtool -K (interface-in) rxvlan off
 "

 like https://github.com/LibreQoE/LibreQoS/issues/26 said.

**Comment by thebracket** [comment]
The good news is that when 1.4 is merged, it does that for you - no more offload file.
