### ISSUE TITLE
New lqosd daemon problem

### ISSUE THREAD

**Issue by gbnpl** [LibreQoE/LibreQoS#196]
Hi,
I just installed the latest main branch and unfortunately there is a problem.
lqosd takes up 60% cpu on two instances when there is no traffic. If the traffic is about 2Gb/s then the cpu load increases drastically (two instances of 80% cpuload each). At the moment loadaverage is at level 9.
When I run 'systemctl status lqosd' :

root@ubntlibreqos:~# systemctl status lqosd
● lqosd.service
     Loaded: loaded (/etc/systemd/system/lqosd.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2023-01-15 00:52:55 CET; 3s ago
   Main PID: 19363 (lqosd)
      Tasks: 21 (limit: 38388)
     Memory: 1.8M
        CPU: 2.807s
     CGroup: /system.slice/lqosd.service
             └─19363 /opt/libreqos/src/bin/lqosd

Jan 15 00:52:57 ubntlibreqos lqosd[19363]: Mapping core #14
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: Mapping core #15
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: Mapping core #16
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: Mapping core #17
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: Mapping core #18
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: Mapping core #19
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: libbpf: Kernel error message: Cannot find specified filter chain
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: No egress program to detach for ifindex 4 (err:-22)
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: Error: Class doesn't support blocks.
Jan 15 00:52:57 ubntlibreqos lqosd[19363]: We have an error talking to the kernel

I have Xeon 2x10 CORE. In Proxmox I share 2 sockets and 20 cores for VM with LibreQoS. In this Proxmox machine is only this one VM.
Ubuntu 5.15.0-58-generic.
Dell R620 - Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
NIC - Intel x520 (2x10Gb/s)

I think something is wrong with lqosd.
Please help.
Thx
Tomasz Andres

**Comment by dtaht** [comment]
Change the polling interval to 100ms.

**Comment by dtaht** [comment]
Also, quick support is best found in the #libreqos:matrix.org chat room - hit @dtaht:matrix.org up for an invite...

**Comment by thebracket** [comment]
The CPU usage is something we're working on right now.

In the meantime, you can try raising the sampling interval for queues (web
gui, config, tuning) to a large number (say 10000).

Roughly how many devices are you shaping?

**Comment by gbnpl** [comment]
... about 2000 devices

**Comment by gbnpl** [comment]
are these messages normal?

Jan 15 02:31:03 ubntlibreqos lqosd[32500]: libbpf: Kernel error message: Cannot find specified filter chain
Jan 15 02:31:03 ubntlibreqos lqosd[32500]: No egress program to detach for ifindex 5 (err:-22)
Jan 15 02:31:04 ubntlibreqos lqosd[32500]: Error: Class doesn't support blocks.
Jan 15 02:31:04 ubntlibreqos lqosd[32500]: We have an error talking to the kernel

**Comment by thebracket** [comment]
In the current pre alpha, yes. Lqosd is trying to unload any previous XDP
filters, and isn't able to do so - because there aren't any. That'll be
cleaned up as we move towards a beta of 1.4

**Comment by dtaht** [comment]
We are looking to get kernel profiles of field deployments, btw. Most of our testing is on bare metal. If you are in a position to run "perf" and supply a flame graph, that is helpful at this point. 

git clone https://github.com/brendangregg/FlameGraph

in the git flamegraph dir

perf record -F 99 -p pidof lqosd -g -- sleep 60
perf script > out.perf
./stackcollapse-perf.pl out.perf > out.folded
./flamegraph.pl --width 7200 out.folded > lqos.svg

I am not sure if github does svgs...

**Comment by gbnpl** [comment]
![lqos](https://user-images.githubusercontent.com/15330326/212521069-365fed4b-8e92-40ed-bb79-960abb051fe4.svg)

**Comment by dtaht** [comment]
thx! woah, that's a lot of locks. Did ratcheting the sample rate way down save your bacon, or do you have another problem? (how long have you been using lbireqos?)

**Comment by gbnpl** [comment]
so I set the sampling to 10000 and it helped a lot.
I have been using libreqos since yesterday :))
I had hashfilters before but with 6Gb traffic qdisc_locking occurred.

liberQoS is what I need :)

**Comment by gbnpl** [comment]
The web panel is very nice. I don't know why but all my IPs are in 'UnknownIPs' and 'Shaped Devices' is empty.

**Comment by dtaht** [comment]
The chat room mentioned is the fastest way to get up and running. You need to tell lqos where the lqos directory is, among other things. The command line is often helpful, Libreqos --validate will validate your rules. Also lqosd is very new, it only landed in head last week (you are running pre-alpha code, tho we do have it running at about 4 ISPs now in test), multiple things are still stubbed out, the v1.3 release was all command line. The documentation talks to the requirements of that mostly.  If you want to live on the bleeding edge, please join us on matrix.org - best way is to tell us your handle there, and we'll invite you in: https://matrix.to/#/!HPuJeVMGSJchAqJqmN:matrix.org?via=matrix.org&via=toke.dk

**Comment by dtaht** [comment]
@gbnpl Please pull down the latest code, it only samples at high resolution the flows you are looking at.

**Comment by dtaht** [comment]
have you also got past your shaped IPs problem yet? If so, please close this bug and rejoice.
