### ISSUE TITLE
Splynx Integration Bug

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#204]
devops@libreqos:/LibreQoS/src$ python3 integrationSplynx.py 
Traceback (most recent call last):
  File "/home/devops/LibreQoS/src/integrationSplynx.py", line 3, in <module>
    from integrationCommon import isIpv4Permitted
  File "/home/devops/LibreQoS/src/integrationCommon.py", line 406
    match node.type:
          ^
SyntaxError: invalid syntax
devops@libreqos:/LibreQoS/src$

_Originally posted by @blongwe in https://github.com/LibreQoE/LibreQoS/discussions/130#discussioncomment-4708406_

**Comment by rchac** [comment]
@blongwe I think your python version is <3.10. Please check by running ```python3 --version```. If so, you can upgrade to Ubuntu Server 22.04 or manually upgrade python to v3.10.

**Comment by blongwe** [comment]
> @blongwe I think your python version is <3.10. Please check by running ```python3 --version```. If so, you can upgrade to Ubuntu Server 22.04 or manually upgrade python to v3.10.

Will try the python upgrade failing which I will do the Ubuntu upgrade

**Comment by dtaht** [comment]
Done?
