### ISSUE TITLE
Solid Error Messages pass

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#209]
In this case, we threw an error, saying what happened, and where it happened, but not on what it happened.

A pass through the code before release, finding all the possible errors and trapping them properly will be of help (not fun to do i the heat of coding, can wait)

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /opt/libreqos/src/rust/lqos_bus/src/bus/client.rs:13:65

I have a scar here: I was trying to deploy a new product to production, written in java. I didn't have source to most of it, and the developers kept blaming the jvm all the problems my team was having. One night, I managed to acquire access to their repos, and grepped through all the Try...catch blocks and discovered that 83% of them had no error handling at all. There was a "come to jesus" meeting the next morning, where I said that I wasn't taking another build without 100% coverage and error logging.
About a week later, we started catching up on sleep.

That said, it's ok to code fast for a while, then take an error checking pass, as C comprehensive error checking gets in the way. There are all sorts of obscure bugs that can only be caught by doing the right thing at common C errno messages, whether they be EINTR (which usually means retry the operation), or ENOBUFS (wait, retry), that can only be discovered by reading the C man pages or deeply inspecting the C or kernel library itself. 

It would be great if rust had a mode where it said, you need to check for these X error conditions, from the OS, and we developed templates for how to handle each.

**Comment by dtaht** [comment]
Some methods for signal handlers, which bear thinking about deeply: #202

as for errnos, I will go looking for comprehensive checking of those in other system daemons at some point (but I too do not want to go through the tedium of this right now)

**Comment by thebracket** [comment]
As of the last commit, there are no more `unwrap` calls that can cause a panic. They have all either been replaced with `unwrap_or`, `unwrap_ok_or` (which turns an unwrap into an error type that can be handled) or removed.

I still have some more `?` to trace.

**Comment by dtaht** [comment]
Applause. While not necessarily holding open this bug, throwing a warning in the future at least on compiles would be useful? We could close it and refer to it 209 whenever something crops up.

Shes real fine my 209, my 2 oh nine

(with apologies to the beach boys)

**Comment by interduo** [comment]
Its almost midnight here. I see some notifications... so many code to repair this bug in a good way.
LOL I will test all my cases next day morning.

**Comment by dtaht** [comment]
In general, this is sort of a checklist item - are we trapping errnos properly, and I am anal about EAGAIN, etc. so I will refer to it in the future as 209 whenever I review code that doesn't comply... and I have not reviewed any code of late at all....
