### ISSUE TITLE
LibreQoS.py - errors with OnAStick = True, (Error: Cannot delete qdisc with handle of zero.)

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#214]
When `OnAStick = True`  - there is one problem running LibreQoS.py.

It always shows: "Error: Cannot delete qdisc with handle of zero." during reloading.

This code range here: https://github.com/LibreQoE/LibreQoS/blob/main/src/LibreQoS.py#L78-L79
There should be a condition when `OnAStick = True` with only one command `tc delete interfaceA` 

There is another range needs to be a little rewriten:
https://github.com/LibreQoE/LibreQoS/blob/main/src/LibreQoS.py#L1061-L1075
For `OnAStick = True`.

Am I correct @rchac?

**Comment by interduo** [comment]
```
Up ParentClassID: 0x9:
ClassMinor: 0x3
Up ParentClassID: 0xa:
ClassMinor: 0x3
Up ParentClassID: 0xb:
ClassMinor: 0x3
Up ParentClassID: 0xc:
ClassMinor: 0x3
Up ParentClassID: 0xd:
ClassMinor: 0x3
Up ParentClassID: 0xe:
ClassMinor: 0x3
Up ParentClassID: 0xf:
ClassMinor: 0x3
Up ParentClassID: 0x10:
ClassMinor: 0x3
Error: Cannot delete qdisc with handle of zero.
Error: Cannot delete qdisc with handle of zero.
Executing linux TC class/qdisc commands
Executed 13017 linux TC class/qdisc commands
Executed 13017 linux TC class/qdisc commands
Executing XDP-CPUMAP-TC IP filter commands
Executed 8086 XDP-CPUMAP-TC IP filter commands
Queue and IP filter reload completed in 5.3 seconds
	TC commands: 	3.2 seconds
	XDP setup: 	 0 seconds
	XDP filters: 	 2.1 seconds
refreshShapers completed on 24/01/2023 16:27:55

```

**Comment by rchac** [comment]
Could you please test the https://github.com/LibreQoE/LibreQoS/tree/attemptFix3235 branch to see if it resolves it for you?

**Comment by interduo** [comment]
@rchac I did:
git cherry-pick https://github.com/LibreQoE/LibreQoS/commit/1c2086e7a80bc55e33fd2a2abd0ce5454225a42c

Now when starting LibreQoS.py i go another error here:

```
Generated parent nodes created
Error: Failed to find qdisc with specified handle.
Executing linux TC class/qdisc commands
Error: Exclusivity flag on, cannot modify.
Command failed linux_tc.txt:2
Executed 13013 linux TC class/qdisc commands
```

Here is full log:
http://kłopotek.pl/debug_mode_libreqos.txt

**Comment by interduo** [comment]
Also `./LibreQoS.py --clearrules` generates an error

```
lqosd is running
Error: Failed to find qdisc with specified handle.
```

**Comment by rchac** [comment]
What are the interfaces for interfaceA and interfaceB? I think some aspect of the VLAN/interrface name is causing an issue

**Comment by interduo** [comment]
@rchac 

```
grep interface ispConfig.py | grep =
interfaceA = 'ens16np0'
interfaceB = 'ens16np0'
```

**Comment by interduo** [comment]
I tried to # interfaceB but there was an error after:
```
./LibreQoS.py 
Traceback (most recent call last):
  File "/opt/libreqos/src/./LibreQoS.py", line 21, in <module>
    from ispConfig import sqm, upstreamBandwidthCapacityDownloadMbps, upstreamBandwidthCapacityUploadMbps, \
ImportError: cannot import name 'interfaceB' from 'ispConfig' (/opt/libreqos/src/ispConfig.py)

```

**Comment by interduo** [comment]
@rchac after aacf6b058e82b459d1a73630d249994e23b2ddd1 commit I see this error only on first time `LibreQoS.py`
