### ISSUE TITLE
LibreQoS.py - too much verbose messages

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#225]
**Now:**
```
# ./LibreQoS.py | grep --count ' to circuit: '
Error: Cannot delete qdisc with handle of zero.
3230
```

**Recommended:**
This information about every circuit ID is not needed here.
We can show it with `--debug` parameter.
I suggest to summarize and show all circuits count.

**Comment by dtaht** [comment]
@rchac it helps to create a (sometimes mistaken! :)) feel "for progress", by closing a bug and assigning it to a milestone, so the progress meter moves. It also helps with writing release notes (a bit, not strictly necessary)
