### ISSUE TITLE
lqos_node_manager/LibreQoS.py - two different validations of ShapedDevices.csv file

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#226]
Command `./LibreQoS.py --validate`
gives me:
```
lqosd is running
network.json passed validation
ShapedDevices.csv passed validation
```

whereas lqos_node_manager sends an many errors to journal
```
Jan 24 16:22:51 libreqos-new lqos_node_manager[9571]: Error: Error reading Device line: StringRecord(["21881", " 5781", " cf9", " 3321", "", "", "172.19.19.32", "", " 500", " 250", " 500", " 250", " KOMENTARZ"])
```

Exact line of ShapedDevices.csv is:
`21881, 5781, cf9, 3321,,,"172.19.19.32",, 500, 250, 500, 250, KOMENTARZ`

**Comment by rchac** [comment]
My best guess is that your ShapedDevices.csv not enclosing the strings (21881, 5781, cf9, etc) with quotes causes it to have a problem where it reads the space in-between entries and places them as part of each string, breaking parsing the numbers.

If you change the line to this does it help?
```21881,5781,cf9,3321,,,"172.19.19.32",,500,250,500,250,"KOMENTARZ"```

**Comment by dtaht** [comment]
I have been struggling with the csv validation myself. I ended up writing/leveraging my own parser, which had trouble not only with hash comments (fixed in some other bug report), but with detecting the first line as a header or not, as well as the last. It also threw errors on stuff that should be strings and wasn't

Lastly, I don't understand what the "primary key" is. In the example, the circuit-id is replicated twice, so I assume that it is that + something. What is that something that consistently is supposed to be a truly unique identifier?

**Comment by interduo** [comment]
I will check that but the allowed syntax should be the same to LibreQoS.py and lqod_node_manager. Its 17pm here. I will check all the things tommorow.

**Comment by interduo** [comment]
@rchac 

Now the situation is like that:
```
root@libreqos-new:/opt/libreqos/src# ./LibreQoS.py 
lqosd is running
refreshShapers starting at 25/01/2023 09:02:39
Not first time run since system boot.
Validating input files 'ShapedDevices.csv' and 'network.json'
/opt/libreqos/src/./LibreQoS.py:425: UserWarning: Rust failed to validate ShapedDevices.csv
  if (validateNetworkAndDevices() == True):
/opt/libreqos/src/./LibreQoS.py:425: UserWarning: "DEVICE DECODE: Err(invalid digit found in string)"
  if (validateNetworkAndDevices() == True):
network.json passed validation
ShapedDevices.csv passed validation
```
I see two problems:
1. Meaning that there are two different validations (not recommended).
Maybe we could use one range of code in two different places? (recommended)

2. There is no information when doing rust validation about line number of ShapedDevices.csv.

**Comment by rchac** [comment]
There is no way to use the exact same code between the python and rust sides but we added this new code to warn what is breaking on the rust side. This info helps.

It looks like the spaces after each comma are being parsed as part of your strings, and breaking parsing as integers.
For example in your file you have:
 ```21881, 5781, cf9, 3321,,,"172.19.19.32",, 500, 250, 500, 250, KOMENTARZ```
So the ```500``` would be parsed as " 500" (space at the beginning) and break int parsing.

Could you please modify ```ShapedDevices.csv`` for all lines` to exclude spaces after commas?
So instead of:
```21881, 5781, cf9, 3321,,,"172.19.19.32",, 500, 250, 500, 250, KOMENTARZ```
You'd have:
```21881,5781,cf9,3321,,,"172.19.19.32",,500,250,500,250,"KOMENTARZ"```

**Comment by interduo** [comment]
I grab vim and did: `%s/ //g`. There is no space now. Rust validates correctly.

**Comment by interduo** [comment]
Please merge branch and close issue then.
