### ISSUE TITLE
mtr support in-band integrated

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#230]
Being able to talk to a customer experiencing problems, trace the paths (both tunneled and direct), and look at the statistics for each device along the way strikes me as a very useful feature. 

Being able to trigger that from a client, and from the gateway actually do it, would be useful. That said, we dont have an ip address to start from and might have to solve this by synthesizing something like that.  You need a raw socket anyway.

There has also been some interesting discussion of revtracert which would find problems with asymmetric routing.

**Comment by rchac** [comment]
Complete with v1.5
