### ISSUE TITLE
lqTools.py - more debug info for selected IP

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#231]
1. Remove debug line:   {show-active-plan-from-ip,tc-statistics-from-ip}

2. Add usage examples somewhere (could be even at the end of --help)

`lqTools.py --debug-ip="172.20.2.42"` should print all debuging info from:
- line from ShapedDevices.csv for this ip,
- node name (from network.json) and procesor/core assigned.
- definition of tc classes linux_tc.txt,
- line from XDP cmd, 
- statistics from tc,

Now there is too much digging.

As it is non critical and we are near next release i add a milestone for v1.5.

**Comment by rchac** [comment]
Deprecating lqTools.py
