### ISSUE TITLE
./build_rust.sh - generates too many warnings about manifest key

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#234]
```
warning: /opt/libreqos/src/rust/lqos_queue_tracker/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqos_node_manager/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqosd/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqosd/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqos_node_manager/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqos_queue_tracker/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqos_queue_tracker/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqos_node_manager/Cargo.toml: unused manifest key: dependencies.notify.feature
warning: /opt/libreqos/src/rust/lqosd/Cargo.toml: unused manifest key: dependencies.notify.feature
```

**Comment by dtaht** [comment]
thx for adding things to the milestone as you go. It helps to watch the progress meter slowly make progress, even when you feel like things are going backwards.

**Comment by interduo** [comment]
@dtaht talking about milestones ...
As a implementer/tester - there are only few issues blocking release. v1.4 would be a perfomance milestone from v1.3 because of XDP_BRIDGE usage.

I suggest making this release as fast as possible - and don't focus attention on non-critical things here (especially lqosd web ui). Most of ISPs don't need UI - we see this as a good toy (we and command line tools are best friend).

**Comment by interduo** [comment]
Back to this issue ... I am not sure but we don't have `.cargo/config` where we have `Cargo.toml` with every package. Could that be a purpose of all those 30+ warnings?

**Comment by dtaht** [comment]
I like the potential, eventually, in lqtop, as a command line tool to dump various things. However, my rust is so poor as to not be able to figure out how to align the overall stats at the top, nor have it give additional commands, and then there is clap to add command line arguments. Any chance you could also take a shot at it?

Even that simplest thing - aligning the overall bandwidth data at the top, and putting in a status bar there also, eludes me: 

https://docs.rs/tui/latest/tui/

**Comment by thebracket** [comment]
I have to admit, I regret being talked into using TUI (an acquaintance came up with it). VERY tempted to go with good old Curses - it's everywhere and it actually works.

**Comment by thebracket** [comment]
The tagged commit fixes all of the build warnings!

**Comment by dtaht** [comment]
Forget the side chat. Great work!

Aside:

Notcurses is better than curses, but didnt seem as nice as tui. Is there another tui-like but better lib for rust? I hate curses form library with a passion and I am impressed with what can be done with tui and other crossterm related stuff so far. Having an easy thread for input vs output, the ability to do 24 bit colors, ohhhh... may the terminal window live again! I long to build stateful database cursors with real locking again....

**Comment by interduo** [comment]
So clean rust building now! Awesome!

**Comment by interduo** [comment]
> I like the potential, eventually, in lqtop, as a command line tool to dump various things. However, my rust is so poor as to not be able to figure out how to align the overall stats at the top, nor have it give additional commands, and then there is clap to add command line arguments. Any chance you could also take a shot at it?
> 
> Even that simplest thing - aligning the overall bandwidth data at the top, and putting in a status bar there also, eludes me: 
> 
> https://docs.rs/tui/latest/tui/

I will check that. This is different programing stack that I do. But I cannot assure that because i got much work to do now :(
