### ISSUE TITLE
lqosd: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#235]
Every second when lqosd is running I get into journal logs:

`journalctl -u lqosd | tail -n1`

```
Jan 31 11:15:28 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:29 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:30 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:31 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:32 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:33 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:34 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:35 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:36 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:37 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Jan 31 11:15:38 libreqos-new lqosd[829]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
```

in lqos_node_manager I've got:
`journalctl -u lqos_node_manager | tail -n1`
```
Jan 31 11:18:43 libreqos-new lqos_node_manager[828]: Error: Error in usage update loop: io error: unexpected end of file
Jan 31 11:18:44 libreqos-new lqos_node_manager[828]: Error: Error in usage update loop: io error: unexpected end of file
Jan 31 11:18:45 libreqos-new lqos_node_manager[828]: Error: Error in usage update loop: io error: unexpected end of file
Jan 31 11:18:46 libreqos-new lqos_node_manager[828]: Error: Error in usage update loop: io error: unexpected end of file
Jan 31 11:18:47 libreqos-new lqos_node_manager[828]: Error: Error in usage update loop: io error: unexpected end of file
Jan 31 11:18:48 libreqos-new lqos_node_manager[828]: Error: Error in usage update loop: io error: unexpected end of file
Jan 31 11:18:49 libreqos-new lqos_node_manager[828]: Error: Error in usage update loop: io error: unexpected end of file
```

I had used scripts:
- ./build_rust.sh,
- removed_pinned_maps.sh

Those errors sometime show and sometime not - I don't know what is calling it. How to debug that case?

**Comment by interduo** [comment]
The errors appears when just reboot machine (and lqosd and lqos_node_manager are started by systemd during system boot). 
If I run screen and daemons by hand the journal is clean of errors.

**Comment by interduo** [comment]
#v+
The top one is exactly the same error message Robert ran into. IIRC, he did:

* Stop everything (daemons)
* `cd src/rust`
* `cargo clean ; cargo build --all --release`
* `cd ..`
* `./build-rust.sh`

And the issue went away. You really *shouldn't* have to do that (Cargo is really smart about dependencies), but it looks a lot like part of the library got out of sync somehow.
#v-

**Comment by interduo** [comment]
```
Jan 31 17:32:25 libreqos-new lqosd[9458]: [2023-01-31T16:32:25Z INFO  lqos_queue_tracker::queue_structure::queing_structure_json_monitor] queuingStructure.csv changed
Jan 31 17:32:25 libreqos-new lqosd[9458]: message repeated 25 times: [ [2023-01-31T16:32:25Z INFO  lqos_queue_tracker::queue_structure::queing_structure_json_monitor] queuingStructure.csv changed]
```
To avoid too many changes triggering - What do You think about that lqosd should check twice with interval of 3 seconds and then do it work?

**Comment by interduo** [comment]
After git pull &. /build_rust.sh i have now:

```
Feb  1 07:35:20 libreqos-new lqosd[824]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Feb  1 07:35:20 libreqos-new lqos_node_manager[825]: Error: Unable to decode/deserialize request
Feb  1 07:35:20 libreqos-new lqos_node_manager[825]: Error: Io(Kind(UnexpectedEof))Feb  1 07:35:20 libreqos-new lqos_node_manager[825]: Error: Unable to decode response from socket.
Feb  1 07:35:20 libreqos-new lqos_node_manager[825]: Error: Error in usage update loop: Unable to decode request
Feb  1 07:35:21 libreqos-new lqosd[824]: thread 'tokio-runtime-worker' panicked at 'overflow when subtracting durations', library/core/src/time.rs:936:9
Feb  1 07:35:21 libreqos-new lqos_node_manager[825]: Error: Unable to decode/deserialize request
Feb  1 07:35:21 libreqos-new lqos_node_manager[825]: Error: Io(Kind(UnexpectedEof))Feb  1 07:35:21 libreqos-new lqos_node_manager[825]: Error: Unable to decode response from socket.
```

**Comment by interduo** [comment]
When I do:
```
systemctl stop lqos_node_manager;
./LibreQoS.py;
systemctl start lqos_node_manager;
```
Errors are gone till reboot.

**Comment by interduo** [comment]
I did it every update (it takes about 12 sec). I am also checking instalation from scratch ocassionaly (thats the purpose of few PRs making changes for  README).

**Comment by thebracket** [comment]
So this is an interesting one. One of the processes obtains time since boot (for a UNIX timestamp), and `clock_gettime` actually fails right after boot. Adding a handler to avoid this problem.

**Comment by interduo** [comment]
Just poke me when do more testing.

**Comment by interduo** [comment]
After reboot there are less errors but

Feb 01 17:29:38 libreqos-new systemd[1]: Started lqos_node_manager.service.       
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Unable to access /run/>
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Error in usage update >
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Unable to access /run/>
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Error in usage update

Maybe we should do some systemd changes that service should be marked as active after some test that lqosd bus is responding?

**Comment by interduo** [comment]
After reboot there are less errors but

Feb 01 17:29:38 libreqos-new systemd[1]: Started lqos_node_manager.service.       
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Unable to access /run/>
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Error in usage update >
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Unable to access /run/>
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Error in usage update

Maybe we should do some systemd changes that service should be marked as active after some test that lqosd bus is responding?

Or do some lazy thing like:
ExecStartPre=/bin/sleep 30

**Comment by interduo** [comment]
After reboot there are less errors but

Feb 01 17:29:38 libreqos-new systemd[1]: Started lqos_node_manager.service.       
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Unable to access /run/>
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Error in usage update >
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Unable to access /run/>
Feb 01 17:29:38 libreqos-new lqos_node_manager[830]: Error: Error in usage update

Maybe we should do some systemd changes that service should be marked as active after some test that lqosd bus is responding?

Or do some lazy thing like:
ExecStartPre=/bin/sleep 30

This last thing for making logs clean

**Comment by dtaht** [comment]
I like the idea of being able to fire off an arbitrary process on up or down events of various subsystems (like re-route me).

but I am very allergic to putting 30 s worth of delay

**Comment by interduo** [comment]
The problem is that after You start process its marked as active. In My opinion process should give back some info like "ok, i am ready, give me tasks" and then systemd should Mark service as active (not earlier at the beggining). There is no state as "prepparing" or "almost active". Sleep is always like work arounds :)

**Comment by dtaht** [comment]
I am deeply concerned that the CS and SRE world as a whole has forgotten about:

https://www.google.com/search?q=random+exponential+backoff

**Comment by interduo** [comment]
This situation no more occur from my last update.

Is LibreQoS.py started automaticly after boot or we need to write an unit service for systemd?

@thebracket if You think that You pushed all required commits for this issue please close this issue.

**Comment by thebracket** [comment]
Currently, `LibreQoS.py` does not run automatically after boot. It probably should, but my first try was a disaster - so I'm holding off on that!

**Comment by rchac** [comment]
The new v1.4 wiki introduces the lqos_scheduler daemon, which runs via systemd only after lqosd is running. This way when you reboot it runs scheduler.py and in turn LibreQoS.py. lqos_scheduler makes sure incremental partial reload happens periodically.
