### ISSUE TITLE
Scheduler.py throws an errors every crontab cycle

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#238]
```
Feb  1 17:40:38 libreqos-new python3[1013]: Failed to run refreshBandwidthGraphs()
Feb  1 17:40:38 libreqos-new python3[1013]: Retrieving circuit statistics
Feb  1 17:40:38 libreqos-new python3[1013]: Computing parent node statistics
Feb  1 17:40:38 libreqos-new python3[1013]: Writing data to InfluxDB
Feb  1 17:40:38 libreqos-new python3[1013]: Failed to run refreshBandwidthGraphs()
Feb  1 17:40:38 libreqos-new python3[1013]: Retrieving circuit statistics
Feb  1 17:40:38 libreqos-new python3[1013]: Computing parent node statistics
Feb  1 17:40:38 libreqos-new python3[1013]: Writing data to InfluxDB
Feb  1 17:40:38 libreqos-new python3[1013]: Failed to run refreshBandwidthGraphs()
```

I dont plan to use influxdb but I would like to have this one for checking if ShapedDevices.csv do changed for reloading. Do I need this now?

Check if variable useInfluxDb=False. If yes then ommit "writing data to influx" and do the rest of scheduler actions.

**Comment by rchac** [comment]
I think your influxDBEnabled value is set to True, because if it was false it would have skipped those functions. Can you please check to confirm if influxDBEnabled = False in ispConfig.py?

**Comment by interduo** [comment]
Sorry for "making bubbles" my mistake.
