### ISSUE TITLE
no info is seen on the dashboard

### ISSUE THREAD

**Issue by behzad-kh** [LibreQoE/LibreQoS#243]
Hello team,

I have brought up the Libreqos v1.4 and the packet is forwarding through the Libreqos node. However, no stats is shown on the dashboard itself.
I have confirmed the packet forwarding through packet capture and ping connectivity between two hosts with Libreqos in between.
I'm using XDP generic with VMXNET3 (Vmware) on the LireQoS
The output of ip link show states that the interfaces (ens192 and ens224) are being loaded with xdpgeneric module.

I have tried to swap the interfaces on the ispConfig.py, but it didn't help
Any feedback is much appreciated.

**Comment by dtaht** [comment]
We are  only just now approaching an alpha of v1.4, and a mite sensitive right now to folk trying it, but very willing to help. The fastest way to get comprehensive support is from our development team in the #libreqos:matrix.org chat room. If you can get an account on matrix, and late me know what it is, I can invite you in. 

Also, pull early and often, new commits land every day...

**Comment by rchac** [comment]
I was experiencing this a few times and found it resolves with this:
1) Stop lqosd and lqos_node_manager
2) ```git pull```
3)
```
cd /src/rust
cargo build --all
```
4)
```
cd /src/
./build_rust.sh
```
5) load lqosd and lqos_node_manager as systemd services (using the [example service files](https://github.com/LibreQoE/LibreQoS/tree/main/src/bin)), then reboot. That ensures everything starts in the correct order.

Please let us know if these steps resolve the dashboard issue for you.

**Comment by behzad-kh** [comment]
@rchac 
I have done the procedure and it is working 👍 thanks
Now I want to shape some IPs. However, the Shaped Devices tab doesn't show the add button to add.
![image](https://user-images.githubusercontent.com/24776390/216767907-f92ea51a-74e2-41f0-822b-df21e7b54bc1.png)

Regards,
 Behzad

**Comment by rchac** [comment]
Adding devices via the GUI is pushed to a future release. For now, it will use ShapedDevicea.csv and network.json and a single source of truth (or whatever integration you us). Once you have a list of your devices as ShapedDevics.csv you can click Refresh Shapers in the top right and it will create all your queues.
