### ISSUE TITLE
Validation problems (hashed or empty lines)

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#244]
```
# ./LibreQoS.py --updateonly
lqosd is running
refreshShapers starting at 03/02/2023 15:36:08
/opt/libreqos/src/./LibreQoS.py:912: UserWarning: Rust failed to validate ShapedDevices.csv
  if (validateNetworkAndDevices() == True):
/opt/libreqos/src/./LibreQoS.py:912: UserWarning: UnequalLengths(
    "At line 3238, position 209667. Expected 13 fields, found 1",
)
  if (validateNetworkAndDevices() == True):
network.json passed validation
ShapedDevices.csv failed validation
/opt/libreqos/src/./LibreQoS.py:1315: UserWarning: Validation failed. Will now exit.
  refreshShapersUpdateOnly()
```

**Now:**
rust try to use last line `"#END OF FILE"`

**Recommended:**
ommit hashed lines

**Comment by thebracket** [comment]
I'm having a bit of trouble replicating this one.

```csv
# This is a comment
Circuit ID,Circuit Name,Device ID,Device Name,Parent Node,MAC,IPv4,IPv6,Download Min Mbps,Upload Min Mbps,Download Max Mbps,Upload Max Mbps,Comment
# This is another comment
"9999","968 Circle St., Gurnee, IL 60031",1,Device 1,AP_7,,"100.64.1.2, 100.64.0.14",,25,5,500,500,
100,1,KOMP_1,100,AP_11,,"10.30.0.204",, 2,2,100,50,COMMENT
101,3,KOMP_3,101,AP_9,,"10.19.7.19",,2,2,10,2,COMMENT
102,4,KOMP_4,102,AP_1,,"5.63.189.26",,2,2,102,102,COMMENT
103,5,KOMP_5,103,,,"10.30.4.128",,2,2,100,50,COMMENT
104,7,KOMP_7,104,,,"10.30.3.49",,2,2,614,204,COMMENT
#END OF FILE
```

Loads perfectly on my end? It doesn't load with a blank line at the end (the Rust is ok with that and Python fails).

**Comment by interduo** [comment]
Why is there a Python code now? Can Python do something that rust can't?

I am thinking about double validation mainly.

**Comment by rchac** [comment]
Python is a lot more accessible for most of us to work with and submit changes for. RUST is way better for the low-level XDP and OS interacting elements, but it falls mostly on Herbert and Dave to find and correct problems there because it's not easy for beginners to work with. Using both together presents certain small issues, like these CSV validation issues, but thats probably outweighed by the benefit of keeping much of the code accessible as python.

**Comment by dtaht** [comment]
@interduo is this resolved now?

**Comment by rchac** [comment]
LibreQoS already omits lines starting with ```#``` on both the Rust and Python ends.
ShapedDevices.csv should not contain any empty lines. That is the cause of the failure.
