### ISSUE TITLE
Thoughts with Dave

### ISSUE THREAD

**Issue by Belyivulk** [LibreQoE/LibreQoS#249]
So, talking with Dave tonight about a few things; first up - quantiles.

If I understand it right the quantile chart (for individual subs) represents the circuit utilization - we can probably just move this to the throughput chart with circuit limits defined (i.e - lines showing the upload/download limits). better again would be if upload was shown as a negative value with a suitable negative limit set. Then we can visually see if a circuit is being maxed. If we can go further, overlaying delays and drops in either direction would be more useful again

Next was a graph showing AP utilization - much the same as individual customer (as a function of the limits for that ap defined) and same again, delays and drops - that would show AP's with poorly performing customers, or poorly performing in their own right. This is messy and poorly thought out i know - sorry. This is in part because....

It lead to the issue of not knowing if the reason for poor performance was the AP, circuit or customers internal network.

There aren't many metrics available to us to work out from the point of observation where the "poor" flow sits relative to the point of observation. Initially i thought we might need a way to "couple" flows; but I think Dave had a potentially easier way around this.

So i think this is why Dave suggested a fast tracert (ebpf based) coupled with specifying the subnets to observe. If we can say "this IP is within our network" and "it has poor rtt" then we can potentially decide to tracert to its edge, measure the latency, and then measure the difference of that, and the flow to work out where we're seeing the increase latency. If we can reasonably determine that the difference in latency is between the last hop and the flows endpoint, we know to look there. Conversely if there is no meaningful difference - we know to look externally.

I'm mostly putting this here as thoughts- they may have zero merit but from a operator perspective being able to narrow focus to the source of a problem (ideally before the customer calls) is useful.

**Comment by dtaht** [comment]
We have some thoughts towards handling some of this in the heimdall branch, and there is no way we can do this in the v1.4 timeframe, so punting.
