### ISSUE TITLE
./lqTools.py - impropper result of  cmd

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#252]
```
root@libreqos-new:/opt/libreqos/src# cat ShapedDevices.csv | grep 172.18.139.5
22322,4119,906,2310,,,"172.18.139.5",,500,500,500, 500,"KOMENTARZ"

root@libreqos-new:/opt/libreqos/src/bin# ./xdp_iphash_to_cpu_cmdline list | grep 172.18.139.5
172.18.139.5/32                               CPU: 0    TC: 1:a2
```

and problematic cmd is:
```
root@libreqos-new:/opt/libreqos/src# ./lqTools.py show-active-plan-from-ip 172.18.139.5
Invalid IP address provided
```

This host was lately added and limit was assigned for circuit by partial reload.

**Comment by rchac** [comment]
Are you running lqos_scheduler? That's the only way this would work under normal conditions.

**Comment by interduo** [comment]
is it not only for influxdb?

**Comment by interduo** [comment]
After running scheduler its working.

Before closing issue - Could You add to TESTING.md what function provides scheduler?

**Comment by interduo** [comment]
There should be also information about default queue limit like:
`Invalid IP address provided (default queue limit is 2000M/2000M)`

**Comment by rchac** [comment]
> After running scheduler its working.
Yay! 
> Before closing issue - Could You add to TESTING.md what function provides scheduler?
Yes, definitely. Will add to both TESTING and wiki.
> There should be also information about default queue limit like:
Good idea. Ok will add.

**Comment by interduo** [comment]
@rchac the limit should not be global upstream limit but parrent generated node limit whitch is described in `generatedPNDownloadMbps` and `generatedPNUploadMbps` in `ispConfig.py`

**Comment by interduo** [comment]
That is working like a charm now! @rchac
