### ISSUE TITLE
Error InfluxDB TCP Latency Circuits

### ISSUE THREAD

**Issue by sebassur07** [LibreQoE/LibreQoS#254]
hello how are you, could you help me with this error since from influxdb the latencies of all the circuits created are not appearing, only the first circuit is appearing
thanks.
ShapedDevices.csv
![image](https://user-images.githubusercontent.com/118370736/217080403-b5b61612-54a8-4e71-a3a0-ed91c1bb4754.png)
Influx
![image](https://user-images.githubusercontent.com/118370736/217080075-8f643e06-d601-4e77-b19c-1fc652be1d6b.png)
Error python3 graphInfluxDB.py
![image](https://user-images.githubusercontent.com/118370736/217079836-5e5d409d-f7ba-4f84-be1f-fce31665bdbc.png)

**Comment by rchac** [comment]
Should be fixed with https://github.com/LibreQoE/LibreQoS/pull/256 Please confirm if this resolves it for you.
