### ISSUE TITLE
Partial reloading problems from other hosts

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#258]
ssh libreqos-new -c 'cd /opt/libreqos/src/; ./LibreQoS.py --updateonly'

gives an:
Error: Class id must be in the format (major):(minor), e.g. 1:12
Error: Class id must be in the format (major):(minor), e.g. 1:12
**(so many times that i deleted it here)**
Error: Class id must be in the format (major):(minor), e.g. 1:12
lqosd is running
refreshShapers starting at 07/02/2023 15:13:44
Rust validated ShapedDevices.csv
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
tc class add dev ens16f1np1 parent 0x1:0x3 classid 0xa2 htb rate 55Mbit ceil 55Mbit
tc qdisc add dev ens16f1np1 parent 0x1:0xa2 fq_codel
tc class add dev ens16f0np0 parent 0x1:0x3 classid 0xa2 htb rate 9Mbit ceil 9Mbit
tc qdisc add dev ens16f0np0 parent 0x1:0xa2 fq_codel
Success

tc class add dev ens16f1np1 parent 0x2:0x3 classid 0xa2 htb rate 38Mbit ceil 38Mbit
tc qdisc add dev ens16f1np1 parent 0x2:0xa2 fq_codel
tc class add dev ens16f0np0 parent 0x2:0x3 classid 0xa2 htb rate 11Mbit ceil 11Mbit
tc qdisc add dev ens16f0np0 parent 0x2:0xa2 fq_codel
Success

updated
updated
**(so many times that i deleted it here)**
updated
Queue and IP filter partial reload completed in 0 seconds
refreshShapersUpdateOnly completed on 07/02/2023 15:13:50
END

I tried to run 3 kinds of command:
ssh sshuser@libreqos -c '/opt/libreqos/src/LibreQoS.py --updateonly' (this gives an error)
ssh sshuser@libreqos -c 'cd /opt/libreqos/src/; ./LibreQoS.py --updateonly' (this also)
ssh sshuser@libreqos -c 'python3 /opt/libreqos/src/LibreQoS.py --updateonly' (this looks ok)

**Comment by interduo** [comment]
OK - I saw the error in log some messages:

```
Feb 07 15:40:09 libreqos-new lqosd[906]: [2023-02-07T14:40:09Z INFO  lqos_utils::file_watcher] queueingStructure.json changed
Feb 07 15:40:09 libreqos-new lqosd[906]: [2023-02-07T14:40:09Z INFO  lqos_queue_tracker::queue_structure::queing_structure_json_monitor] queueingStructure.csv reloaded
Feb 07 15:40:09 libreqos-new lqosd[906]: [2023-02-07T14:40:09Z ERROR lqos_queue_tracker::queue_structure::queue_node] I don't know how to parse key: [idForCircuitsWithoutParentNodes]
Feb 07 15:40:09 libreqos-new lqosd[906]: [2023-02-07T14:40:09Z ERROR lqos_queue_tracker::queue_structure::queue_node] I don't know how to parse key: [idForCircuitsWithoutParentNodes]
```

running ./LibreQoS.py manualy do reloading correctly

**Comment by thebracket** [comment]
Not sure I've run into `[idForCircuitsWithoutParentNodes]` in queueingStructure. I'll see about relaxing that particular error (making it a warning) in the morning, and handle that key correctly.

**Comment by rchac** [comment]
idForCircuitsWithoutParentNodes is used to make binpacking work correctly. It can be skipped over when reading queueingStructure because it's not used outside of the binpacking context.

**Comment by interduo** [comment]
I don't see more errors here after update.

@thebracket please close this if You think all the needed changes are here

**Comment by thebracket** [comment]
Thanks - closing this issue.
