### ISSUE TITLE
VLANs in shaped traffic

### ISSUE THREAD

**Issue by thebracket** [LibreQoE/LibreQoS#26]
Doing a bit of testing early this morning, I ran into an interesting one. I cut over from our current Preseem setup, which has tagged VLANs in the bridge traffic. (It's not ideal, but it's working around some Preseem issues with our proxmox setup; Preseem support and proxmox is not a great mix - long story, they logged in and broke everything a few times!)

This doesn't affect `virtio` interfaces. I had PCI pass-through to an actual Intel 10gb NIC. After banging my head against a wall for a bit, the solution turned out to be to add the following to your offloading configuration:

```
 ethtool -K (interface-out) rxvlan off
 ethtool -K (interface-in) rxvlan off
```

Replace `(interface-out)` and `(interface-in)` with the actual interface names, in my case `enp1s0f0` and ` enp1s0f1` respectively.

Hope that helps!

**Comment by rchac** [comment]
Interesting. Did it continue to work well once setting rxvlan off on both interfaces? If so I can change the documentation, i just want to be sure you didn't experience issues resulting from it.

**Comment by thebracket** [comment]
Once we set `rxvlan`, it worked well.

Using older hardware (Xeon E5-2620 @ 2Ghz, 2 sockets, 12 CPUs excluding hyperthreading, 48 Gb installed), running ProxMox. There's a few other light-duty VMs on the same box (DNS, mostly), but we gave the LibreQOS VM the same virtual hardware as Preseem (10 Gb RAM, no ballooning. 10 sockets, `+pcid`, `numa=1`, using the `q35` machine. Pass-thrpugh PCIe to an Intel X10 dual-port 10 GbE adapter.

Out Internet feed is 2 Gbps, and our peak is only around 1.1 Gbps at night - but it handled that without a problem (around 400 customers). CPU load from `pping` was the biggest consumer, otherwise CPU use was in the 10-20% range by core.

We experimented a bit with various configurations. A mostly flat configuration (each site, with children attached) spreads the load out the best, since sites don't get nested in deep HTB pipes. This gave the best individual latencies, but doesn't do anything to help with congested backhauls. Also a deep site tree, accurately representing backhaul capacities across 49 towers. That saw a couple of CPUs with higher load than the others, but still worked well.

Our final tuning code turned on BPF jit (`sysctl net.core.bpf_jit_enable=1`) for a tiny performance boost. We also added:

```
modprobe sch_htb
echo 1 > /sys/module/sch_htb/parameters/htb_rate_est
```

This enables the HTB schedule monitor kernel module, and enables "rate estimation". You can then do `tc -s class show dev` and get byte counts per HTB site queue, including drops and borrows. It doesn't work with JSON output for some reason, but is pretty easy to parse. That lets you not do the "find parents" dance when counting throughput; you can grab the parent queue throughput directly from the kernel's counters.

It ran well enough that we didn't get a single complaint call. :-)

---

We've since spent a couple of weeks making a system in Rust that does the same thing, but is closely tied to how our network is setup (we have a mix of Cambium, Ubiquiti and Mimosa gear). It's been running 24/7 for a week, and my boss has canceled our Preseem subscription.

One the shaping side, we really only made a handful of changes:

* We run the offload tweak commands on daemon startup, removing the need for a separate tuning script.
* We poll uISP (and cnMaestro!) every 5 minutes and build a "virtual tree" - describing the queues that should be there. Intra-site and AP speed limits are polled from a "manager" program running on a different computer and applied to the virtual queue. The virtual queue is then hashed, and the Linux queues rebuilt only if the previous configuration has a different hash - something has changed. That lets us have Preseem-like "make a change, the shaper picks it up really fast" feel.
* We poll HTB queue stats from the `tc` command rather than tree-chasing.
* Added some logic that counts the actual number of seconds since last time we polled the queues, and uses that as a divisor for calculating Mbit/s (and discards the first result). These poll every minute, but sometimes `sleep` isn't exactly 60 seconds - so this keeps the numbers nicely aligned.
* We run recycle `pping` every 30 seconds rather than every 10. I'm not sure it makes much difference.

Then on the back-end, the "manager" program stores posted data in `influxdb2`, and provides a nice GUI for our support people:
![image](https://user-images.githubusercontent.com/14896751/165090887-87cf07cc-4f2e-41fa-8312-0b43cec39fe3.png)

![image](https://user-images.githubusercontent.com/14896751/165091157-239a6997-59f7-40f6-a093-29c474cc7cc7.png)

So we're super-happy with this project! :-)

**Comment by thebracket** [comment]
Oh, and compiling the XDP code with `o3` makes a small but noticeable difference in overall performance.

**Comment by thebracket** [comment]
An update on the HTB estimator: after running it for a bit, we found that it would sometimes get confused and a deleted/recreated queue would just keep increasing its number of bytes (to a silly degree). I did a bunch of digging, and found out why it isn't the default - it's *really* CPU intensive. So I went back to walking the tree to determine bytes for parent queues, turned it off, and the overall shaper CPU usage dropped noticably.

**Comment by interduo** [comment]
Guys look at https://github.com/xdp-project/xdp-cpumap-tc/issues/7#issuecomment-1231587569

So this means that LibreQoS could support VLANs?

**Comment by rchac** [comment]
Neat. I thought he VLAN header parsing wasn't fully implemented in xdp-cpumap-tc code.

So if you have VLAN traffic passing over the LibreQoS bridge, the traffic will be shaped even if it has a VLAN header. Each host must have a distinct IPv4 though - it just skips any VLAN tags so it won't know if two different VLANs have different rules for the same IPv4.

**Comment by thebracket** [comment]
I can attest to it working - we're shaping traffic on VLANs just fine. :-)
(MPLS isn't going to work - but VLANs work great)

**Comment by interduo** [comment]
@thebracket are You using LibreQoS in one-network-card for network traffic architecture?

**Comment by thebracket** [comment]
No - two NICs, passing through with VLANs inside. The actual architecture
being:
10g fiber -> (virtual Mikrotik router, connected to the internet) -> virtio
-> LibreQoS -> mapped NIC
There is backhaul traffic from various locations arriving on different
VLANs that pass through LibreQOS (well, BracketQOS - we have a massively
customized implementation in-house, but the shaping core is the same) to a
single virtual router that talks to the Internet. On a ProxMox box, it
handles the 2Gbit/s we have just fine.

I'm not sure if running it "on a stick" (1 NIC, in VLAN and out VLAN) would
work, but conceptually it should. I *think* the setup would be:

(At setup)
Create INBOUND VLAN (say 10)
Create OUTBOUND VLAN (say 11)
Create bridge (br0) between ethernet.10 and ethernet.11
Set LibreQOS to list the VLAN interfaces as in/out respectively.

In theory, it'd still support VLANs *inside* that bridge, because the "on a
stick" traffic is passing through without tags.

Unfortunately, I really don't have time to test that concept.

**Comment by dtaht** [comment]
@thebracket 
@tohojo just found and fixed a user after free bug with htb + cake in linux mainline, but the stats problem you had is interesting and I'd like to poke into it further.

Do you intend to release "BracketQos"? in any form? Rust seems like a sane approach in many ways.

**Comment by tohojo** [comment]
Actually it turned out that UAF only affected SFB, so we just fixed that instead of changing anything in CAKE: https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=9efd23297cca530bb35e1848665805d3fcdd7889

**Comment by interduo** [comment]
Connected with https://github.com/LibreQoE/LibreQoS/issues/48

**Comment by MrHamel** [comment]
Is it planned to support matching both IP blocks and VLANs? I'd like to specify both as my various VRFs overlap the same RFC1918 space on different VLANs before hitting a central firewall at the datacenter.

**Comment by rchac** [comment]
@MrHamel It may be possible but @thebracket can speak to how feasible that is.

**Comment by dtaht** [comment]
:ouch:. A network diagram would be helpful here.

**Comment by MrHamel** [comment]
My apologies, I did not get any notifications about this getting updated. The diagram is really simple.

MPLS Core -> LibreQoS -> BGP Edge Router -> Firewall -> Internet.

172.16.0.0/24 for VLAN 10 would be different for 172.16.0.0/24 on VLAN 20, for example. The best way to describe it is that I need more granularity.

**Comment by interduo** [comment]
This works well so we could close that, right?

**Comment by thebracket** [comment]
@MrHamel I've extracted the MPLS feature request into a separate issue: https://github.com/LibreQoE/LibreQoS/issues/184

Reading inside nested VLANs (now with no depth limit, although I've never seen more than two) is working well, so I'm closing this issue and leaving the MPLS one open.
