### ISSUE TITLE
lqtop - some strange characters

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#266]
![image](https://user-images.githubusercontent.com/17087236/218541580-bfc683ec-9789-43cb-a1a3-22114e5feed3.png)

There are some strange characters here. I suspect that it's from UTF-8 charset but I don't know what kind - please add some info to wiki. How is it looks at Your console?

**Comment by thebracket** [comment]
Those are ANSI escape codes to display colours.

**Comment by interduo** [comment]
> Those are ANSI escape codes to display colours.

Is it possible to see colors with SSH connection with lqtop? What is required?
When I do `ls --color` I see colors on console.

**Comment by thebracket** [comment]
You need to be in a terminal type that supports it. It just works for me
with windows SSH or PuTTY? Regular `xterm` I think needs configuration, it
works fine in gterm and similar?

**Comment by interduo** [comment]
I use Ubuntu 22.10 on desktop. I connect to LibreQoS with ssh command.

**Comment by dtaht** [comment]
no, those are the cute up and down arrows, and unicode fonts in many terminals do not work. It is why we cannot have nice things.

**Comment by thebracket** [comment]
Oh! I wish regular ASCII had up and down. Cp437 (which is usually
available) does. I'll see if any of those work.

**Comment by interduo** [comment]
Dont worry about that just use -> or <- :)
