### ISSUE TITLE
Install the Rust development system

### ISSUE THREAD

**Issue by mwangi-kiboi** [LibreQoE/LibreQoS#277]
`cd /opt/libreqos/src/
./build_rust.sh`

While compiling i got this error

`error: package `time v0.3.19` cannot be built because it requires rustc 1.62.0 or newer, while the currently active rustc version is 1.61.0
error: package `clap v4.1.6` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.61.0
`
checking the version

`@libreqos:/opt/libreqos/src$ rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
`

Had to run `apt -y install rust-all` and resolved it.

**Comment by dtaht** [comment]
Thx for all your feedback today! We have had a tendency to just be pulling rust from head, rather than apt. At some point we should stablize on a release to support for a while, but everything is moving very quickly. 

I hope you are well on your way to getting 1.4 running for yourself?

**Comment by mwangi-kiboi** [comment]
yes, managed to set it up. Teething around with the network.json and splynx
