### ISSUE TITLE
Lqosd is not running

### ISSUE THREAD

**Issue by theushervict** [LibreQoE/LibreQoS#283]
./LibreQoS.py
Running Python Version 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
ERROR: lqosd is not running. Aborting

**Comment by rchac** [comment]
Is lqosd running? You can use:
```sudo systemctl status lqosd``` to find out.

**Comment by theushervict** [comment]
root@libreqos:/opt/libreqos/src/bin# sudo ./lqosd
sudo: ./lqosd: command not found

**Comment by rchac** [comment]
Thanks. Did you use the .deb installer, or follow the [v1.4 wiki](https://github.com/LibreQoE/LibreQoS/wiki/v1.4)? I ask because ```./build_rust.sh``` has apparently not been run yet. That should happen as part of the .deb installer as well as v1.4 documentation.

**Comment by theushervict** [comment]
Yes I have run it. this first 
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
and then this 
cd /opt/libreqos/src/
./build_rust.sh

**Comment by rchac** [comment]
What shows up in the ```/opt/libreqos/src/bin``` folder?
You can use ```ls /opt/libreqos/src/bin``` to check.

**Comment by rchac** [comment]
Also please check for errors that might have occurred when running
```
cd /opt/libreqos/src/
./build_rust.sh
```

**Comment by theushervict** [comment]
> What shows up in the `/opt/libreqos/src/bin` folder? You can use `ls /opt/libreqos/src/bin` to check.

lqosd.service.example  lqos_node_manager  lqos_node_manager.service.example  lqos_scheduler.service.example  lqtop  lqusers  Rocket.toml  static  xdp_iphash_to_cpu_cmdline  xdp_pping

**Comment by rchac** [comment]
It did not complete ```./build_rust.sh```. Please check for errors that might have occurred when running
```
cd /opt/libreqos/src/
./build_rust.sh
```

**Comment by theushervict** [comment]
Checking that Rust is uptodate
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: checking for self-updates

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.68.0 (2c8cc3432 2023-03-06)

info: cleaning up downloads & tmp directories
Please wait while the system is compiled. Service will not be interrupted during this stage.
   Compiling serde_derive v1.0.153
   Compiling thiserror-impl v1.0.39
   Compiling regex v1.7.1
   Compiling cexpr v0.6.0
   Compiling libbpf-sys v1.1.1+v1.1.0
   Compiling tokio-macros v1.8.2
   Compiling aho-corasick v0.7.20
   Compiling regex-syntax v0.6.28
   Compiling log-once v0.4.0
   Compiling humantime v2.1.0
error: failed to run custom build command for `libbpf-sys v1.1.1+v1.1.0`

Caused by:
  process didn't exit successfully: `/opt/libreqos/src/rust/target/release/build/libbpf-sys-3a2343f10e6f3e1e/build-script-build` (exit status: 101)
  --- stderr
  make: *** No targets specified and no makefile found.  Stop.
  thread 'main' panicked at 'pkg-config is required to compile libbpf-sys using the vendored copy of libbpf', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-1.1.1+v1.1.0/build.rs:106:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
    Finished release [optimized] target(s) in 0.41s
    Finished release [optimized] target(s) in 0.31s
    Finished release [optimized] target(s) in 0.27s
    Finished release [optimized] target(s) in 1.03s
    Finished release [optimized] target(s) in 0.27s
Installing new binaries into bin folder.
Installing lqosd in bin folder
cp: cannot stat 'target/release/lqosd': No such file or directory
mv: cannot stat '../bin/lqosd.new': No such file or directory
Installing lqtop in bin folder
Installing xdp_iphash_to_cpu_cmdline in bin folder
Installing xdp_pping in bin folder
Installing lqos_node_manager in bin folder
Installing lqusers in bin folder
    Finished release [optimized] target(s) in 0.37s
lqos_node_manager is running as a service. Restarting it. You may need to enter your sudo password.
-----------------------------------------------------------------
Don't forget to setup /etc/lqos.conf!
Template .service files can be found in bin/

**Comment by thebracket** [comment]
Aha. You need to install "linux-tools" for your kernel version.

**Comment by rchac** [comment]
Use
```
sudo apt-get install linux-tools-`uname -r`
```

**Comment by theushervict** [comment]
> sudo apt-get install linux-tools-`uname -r`

Running kernel seems to be up-to-date.

The processor microcode seems to be up-to-date.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

No VM guests are running outdated hypervisor (qemu) binaries on this host.

run again?
cd /opt/libreqos/src/
./build_rust.sh

**Comment by rchac** [comment]
Yes, please try
```
cd /opt/libreqos/src/
./build_rust.sh
```

**Comment by theushervict** [comment]
> Yes, please try
> 
> ```
> cd /opt/libreqos/src/
> ./build_rust.sh
> ```

Checking that Rust is uptodate
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: checking for self-updates

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.68.0 (2c8cc3432 2023-03-06)

info: cleaning up downloads & tmp directories
Please wait while the system is compiled. Service will not be interrupted during this stage.
   Compiling toml_datetime v0.6.1
   Compiling serde_spanned v0.6.1
   Compiling serde_json v1.0.94
   Compiling libbpf-sys v1.1.1+v1.1.0
   Compiling csv v1.2.1
   Compiling lqos_sys v0.1.0 (/opt/libreqos/src/rust/lqos_sys)
   Compiling lqos_utils v0.1.0 (/opt/libreqos/src/rust/lqos_utils)
   Compiling bincode v1.3.3
error: failed to run custom build command for `libbpf-sys v1.1.1+v1.1.0`

Caused by:
  process didn't exit successfully: `/opt/libreqos/src/rust/target/release/build/libbpf-sys-3a2343f10e6f3e1e/build-script-build` (exit status: 101)
  --- stderr
  make: *** No targets specified and no makefile found.  Stop.
  thread 'main' panicked at 'pkg-config is required to compile libbpf-sys using the vendored copy of libbpf', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-1.1.1+v1.1.0/build.rs:106:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
    Finished release [optimized] target(s) in 0.28s
    Finished release [optimized] target(s) in 0.28s
    Finished release [optimized] target(s) in 0.26s
    Finished release [optimized] target(s) in 0.40s
    Finished release [optimized] target(s) in 0.26s
Installing new binaries into bin folder.
Installing lqosd in bin folder
cp: cannot stat 'target/release/lqosd': No such file or directory
mv: cannot stat '../bin/lqosd.new': No such file or directory
Installing lqtop in bin folder
Installing xdp_iphash_to_cpu_cmdline in bin folder
Installing xdp_pping in bin folder
Installing lqos_node_manager in bin folder
Installing lqusers in bin folder
    Finished release [optimized] target(s) in 0.29s
lqos_node_manager is running as a service. Restarting it. You may need to enter your sudo password.
-----------------------------------------------------------------
Don't forget to setup /etc/lqos.conf!
Template .service files can be found in bin/

Run sudo rust/remove_pinned_maps.sh before you restart lqosd
This ensures that any data-format changes will apply correctly.

**Comment by rchac** [comment]
Looks like pkg-config was not installed. [This step](https://github.com/LibreQoE/LibreQoS/wiki/v1.4#install-dependencies-from-apt-and-pip) may have been skipped.

```
sudo apt-get install -y python3-pip clang gcc gcc-multilib llvm libelf-dev git nano graphviz curl screen llvm pkg-config linux-tools-common linux-tools-`uname -r` libbpf-dev
```

**Comment by theushervict** [comment]
> Looks like pkg-config was not installed. [This step](https://github.com/LibreQoE/LibreQoS/wiki/v1.4#install-dependencies-from-apt-and-pip) may have been skipped.

I'm sure I did all the steps, but I'll try again no problem.

**Comment by rchac** [comment]
Woo! Awesome 
![giphy](https://user-images.githubusercontent.com/22501920/226501510-4e223388-c78a-404f-94f6-05247ca5b51a.gif)

You should now be able to run
```
sudo systemctl start lqosd
sudo systemctl restart lqos_node_manager
```

**Comment by theushervict** [comment]
> sudo systemctl status lqosd

● lqosd.service
     Loaded: loaded (/etc/systemd/system/lqosd.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-03-21 01:47:54 UTC; 9min ago
   Main PID: 5379 (lqosd)
      Tasks: 23 (limit: 28752)
     Memory: 314.8M
        CPU: 2.616s
     CGroup: /system.slice/lqosd.service
             └─5379 /opt/libreqos/src/bin/lqosd

mar 21 01:47:54 libreqos systemd[1]: Started lqosd.service.
mar 21 01:47:57 libreqos lqosd[5379]: [2023-03-21T01:47:57Z WARN  lqos_bus::bus::unix_socket_server] Listening on: /run/lqos/bus

**Comment by theushervict** [comment]
![image](https://user-images.githubusercontent.com/128437393/226502190-88782682-d150-4246-8a9a-a1935af11719.png)

**Comment by rchac** [comment]
Wonderful. Thank you for your patience as we worked to get this solved.
