### ISSUE TITLE
Help to rooted network

### ISSUE THREAD

**Issue by theushervict** [LibreQoE/LibreQoS#284]
how to implement libre qos in a rooted network
I have implemented it but it only raises 200mb

Edit:
I have also tried to open:
ShapedDevices.csv
network.json

but it doesn't exist

ls
bin               influxDBdashboardTemplate.json  integrationUISP.py    LibreQoS.py            mikrotikDHCPRouterList.csv  README.md                  testGraph.py
build_dpkg.sh     integrationCommon.py            ispConfig.example.py  lqos.conf.new.discuss  mikrotikFindIPv6.py         rust                       TESTING-1.4.md
build_rust.sh     INTEGRATION_HOWTO.md            ispConfig.py          lqos.example           network.example.json        scheduler.py               testIP.py
error_handling    integrationRestHttp.py          ispConfig.py.backup   lqTools.py             __pycache__                 ShapedDevices.example.csv
graphInfluxDB.py  integrationSplynx.py            liblqos_python.so     lqusers.toml           pythonCheck.py              testdata

**Comment by dtaht** [comment]
There are example ShapedDevices.csv.example and network.json.example files that you can copy over and use as a template for your use case.

**Comment by dtaht** [comment]
In general it is faster to debug things if you were to join the #libreqos:matrix.org channel. Also our UISP expert @rchac is still asleep (available approximately 6-6 PST).

**Comment by thebracket** [comment]
**Important**: You've given the world your password in your `uispAuthToken` up there. I'd recommend editing the message!

I'll post some more momentarily, wanted to let you know.

**Comment by dtaht** [comment]
I deleted your comment with that password, but do change it when you get a chance.

**Comment by theushervict** [comment]
I had already deleted it from my apis uisp

**Comment by theushervict** [comment]
Could you help me with the uisp integration?

I have configured the ispConfig.py file
automaticImportUISP = True
uispAuthToken = 'xxxxxxxx'
Everything before /nms/ on your UISP instance
UISPbaseURL = 'https://uisp.onnestech.com.ve/nms/'
UISP Site - enter the name of the root site in your network tree
to act as the starting point for the tree mapping
uispSite = 'https://uisp.onnestech.com.ve/nms/sites'
Strategy:

python3 integrationUISP.py
Running Python Version 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Loading Data from UISP
Traceback (most recent call last):
File "/opt/libreqos/src/integrationUISP.py", line 228, in
importFromUISP()
File "/opt/libreqos/src/integrationUISP.py", line 223, in importFromUISP
case "full": buildFullGraph()
File "/opt/libreqos/src/integrationUISP.py", line 87, in buildFullGraph
sites = uispRequest("sites")
File "/opt/libreqos/src/integrationUISP.py", line 17, in uispRequest
return r.json()
File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.10/json/init.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

replace with "xxxx"

**Comment by rchac** [comment]
UISPbaseURL should be 'https://uisp.onnestech.com.ve' not 'https://uisp.onnestech.com.ve/nms/'

**Comment by theushervict** [comment]
> UISPbaseURL should be 'https://uisp.onnestech.com.ve' not 'https://uisp.onnestech.com.ve/nms/'

ok edit , and try again
thanks for your answer

**Comment by thebracket** [comment]
The `uispAuthToken` is generated in UISP so you don't have to share passwords. Login to UISP (the NMS side), go to Settings and then Users. Click the `Create New API Token` button and give it a name, it'll give you some text to copy and use as your `uispAuthToken` in LibreQoS.

**Comment by dtaht** [comment]
yay! Send us a screenshot of it working (in klingon mode?). It always makes us smile.

**Comment by theushervict** [comment]
![image](https://user-images.githubusercontent.com/128437393/226628042-6372395c-e0a2-4b0a-8412-a61a6867b16f.png)


> yay! Send us a screenshot of it working (in klingon mode?). It always makes us smile.

**Comment by dtaht** [comment]
That looks lovely. However it is still specific to you and we don't need to see that. The screenshot I was hoping for was of the gui, pushing traffic.

**Comment by theushervict** [comment]
> That looks lovely. However it is still specific to you and we don't need to see that. The screenshot I was hoping for was of the gui, pushing traffic.

that's the other question
Right now it is disconnected because when I implement it I only get up 200mb
If I connect it now, will it work on the entire rooted network?

**Comment by theushervict** [comment]
> Regrettably I don't know what hardware you have here. A decent 16 core xeon can push well over 10Gbits. In all the cases you listed above, each client is configured for less than 200Mb.
> 
> Anyway, if you cannot get more than 200Mbit total through the bridge, that indicates another problem.
> 
> You can deploy in "monitor mode", and not do any shaping, to see if your hardware can at least forward the traffic at the rates you need.

hp proliant dl360 g7
Ethernet Converged Network Adapters X520
![image](https://user-images.githubusercontent.com/128437393/226633579-dcff0308-b637-4cec-9033-22961a0eff3e.png)

**Comment by thebracket** [comment]
I'm a little confused by "routed" network - are you hoping to have LibreQoS
do routing? LibreQoS is a transparent bridge, and won't do any routing -
but it will happily pass routing data such as OSPF, IS-IS, BGP, etc.
through the bridge. Ideally, there shouldn't be any IP addresses on the two
interfaces carrying traffic (one facing your router attached to the
Internet, one facing the customer side of the network) - having an IP
address really kills performance, because the Linux kernel then tries to
interact with each packet.

**Comment by theushervict** [comment]
> I'm a little confused by "routed" network - are you hoping to have LibreQoS do routing? LibreQoS is a transparent bridge, and won't do any routing - but it will happily pass routing data such as OSPF, IS-IS, BGP, etc. through the bridge. Ideally, there shouldn't be any IP addresses on the two interfaces carrying traffic (one facing your router attached to the Internet, one facing the customer side of the network) - having an IP address really kills performance, because the Linux kernel then tries to interact with each packet.

Yes, I know that it is transparent between the two
All my network after the core is routed by node

**Comment by theushervict** [comment]
> 1. What CPU model?
> 2. Are you using xdp bridge or regular linux bridge?
> 3. Your network.json should be changed to balance your sites across each CPU. I can show you how to do that if you send the full network.json

model name      : Intel(R) Xeon(R) CPU           X5570  @ 2.93GHz

**Comment by rchac** [comment]
You are supposed to use the linux bridge OR xdp bridge, but not both. Please remove the bridge configuration from netplan .yaml. Then run ```sudo netplan apply``` to remove the linux bridge.

You'll need to
```
sudo systemctl restart lqosd
```

Also you can try to split the network.json by eliminating the top level node. That would share the CPU load across more cores and allow you to get closer to 1 Gbit. If you need help just share the full network.json with us and i can edit it for you.

**Comment by theushervict** [comment]
> You are supposed to use the linux bridge OR xdp bridge, but not both. Please remove the bridge configuration from netplan .yaml. Then run `sudo netplan apply` to remove the linux bridge.
> 
> You'll need to
> 
> ```
> sudo systemctl restart lqosd
> ```
> 
> Also you can try to split the network.json by eliminating the top level node. That would share the CPU load across more cores and allow you to get closer to 1 Gbit. If you need help just share the full network.json with us and i can edit it for you.

![image](https://user-images.githubusercontent.com/128437393/226643705-fd84bd7f-2384-4a5d-ad93-89b7f131aa3d.png)
ok I'll try and I'll be warning
thank you all for your patience

**Comment by theushervict** [comment]
> You are supposed to use the linux bridge OR xdp bridge, but not both. Please remove the bridge configuration from netplan .yaml. Then run `sudo netplan apply` to remove the linux bridge.
> 
> You'll need to
> 
> ```
> sudo systemctl restart lqosd
> ```
> 
> Also you can try to split the network.json by eliminating the top level node. That would share the CPU load across more cores and allow you to get closer to 1 Gbit. If you need help just share the full network.json with us and i can edit it for you.

![image](https://user-images.githubusercontent.com/128437393/226644080-64c4844d-e5b0-46e1-93dc-19a4dfbe0923.png)

ok I'll be testing

thank you all for your patience

**Comment by theushervict** [comment]
Closed 
Tnx for help me.
