### ISSUE TITLE
Libre Qos Throughput

### ISSUE THREAD

**Issue by theushervict** [LibreQoE/LibreQoS#285]
my network only consumes 900 mb

![image](https://user-images.githubusercontent.com/128437393/226681623-d513f90f-f7e1-468c-aed5-0bb17940b6ed.png)

libre Qos marks 1.8g

![image](https://user-images.githubusercontent.com/128437393/226682056-ebfd3dcf-4b2f-48fe-bf61-c2e6323b0499.png)

Why is this happening

**Comment by thebracket** [comment]
Or did I misunderstand, and you see a different number between the "current throughput" chart and the top graph (looks like UISP?). You might have both the XDP bridge and the Linux bridge running, perhaps? (You want one or the other - I recommend the xdp bridge for performance)

**Comment by theushervict** [comment]
> Or did I misunderstand, and you see a different number between the "current throughput" chart and the top graph (looks like UISP?). You might have both the XDP bridge and the Linux bridge running, perhaps? (You want one or the other - I recommend the xdp bridge for performance)

I don't just have the Xdp bridge
if i set everything to 1800mb is my total capacity

**Comment by theushervict** [comment]
![image](https://user-images.githubusercontent.com/128437393/226697023-ef15ae14-78a5-4bcf-834c-a1c65995c7ce.png)

![image](https://user-images.githubusercontent.com/128437393/226697117-0136db23-49bf-47d6-a56b-161408d2e271.png)

**Comment by dtaht** [comment]
I think you are observing a bug that has landed in the past few days from head. Could you checkout v1.4-rc2 and see if this goes away?

**Comment by theushervict** [comment]
I still can't solve this bug

**Comment by dtaht** [comment]
please join us in the chat. We are just as puzzled as you are.

**Comment by theushervict** [comment]
I've rechecked everything and can't find anything out of place

**Comment by dtaht** [comment]
Please join us in the chat? Our key folk will not be awake for at least another hour and a half, however.

https://matrix.to/#/#libreqos:matrix.org
