### ISSUE TITLE
Death wished to the last String in the cake parser

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#289]
The only string left in the cake parser is the fwmark, which is a hex value that does not have 0x in front of it if it is zero. 

I hatest strings, hatest them, hates them forever....

**Comment by thebracket** [comment]
For some reason, the commit tag didn't close the issue.

**Comment by thebracket** [comment]
I'm actually optimizing the circuit_queue.html renderer right now (it's
really flabby). I think there will be a new "CakeTransit" type that only
sends the data we're using. We'll still have the rest of the data if we
want to use it later, but it'll elide a whole bunch of network traffic.
