### ISSUE TITLE
Upgrading from 1.3 to 1.4 lost step

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#290]
@rchac please add this to wiki/readme
```
rm /usr/local/sbin/offloadOff.sh
systemctl disable offloadOff.service 
rm /etc/systemd/system/offloadOff.service

```

**Comment by rchac** [comment]
By the way, @interduo, you should now have wiki access. =)

**Comment by rchac** [comment]
By the way, @interduo, you should now have wiki access. =)

**Comment by interduo** [comment]
@rchac do You know is it possible to dump wiki to file in repository or make some synchronization?
I am asking about that because readme in file is very usable.

**Comment by rchac** [comment]
@interduo Doesn't look like there's a straightforward way quite yet. :/ https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content
