### ISSUE TITLE
10sec of packet capture is not enough

### ISSUE THREAD

**Issue by dtaht** [LibreQoE/LibreQoS#291]
Your typical speedtest runs for about 30seconds, maybe 40. Being able to take a capture of those, start to finish, would be enlightening. Similarly, netflix occilates on a 10sec interval. Other forms of network misbehavior only show up on 1minute intervals, and thus 5 minutes of packet cap would be good. Very little can be discerned in 10s.

Also, in the long run, more than one person able to take a cap (say, 4) would be useful. Yes, I know both of these have extreme memory requirements, and the code should perhaps make utterly sure we have a grip on how much memory will be used up before starting one.

**Comment by dtaht** [comment]
An explicit start and stop button might help. or Done Capturing.

**Comment by dtaht** [comment]
use the circuit-id for the output file with a timestamp range embedded.

**Comment by rchac** [comment]
Solved with #293
