### ISSUE TITLE
Question regarding Mikrotik PPPoE

### ISSUE THREAD

**Issue by dinbhar** [LibreQoE/LibreQoS#300]
Hi,

We use third-party billing (aaa) system and customer dynamic queues sit on Mikrotik routers and we use both IPv4 and IPv6. Customer ranges from 10Mbps to 300Mbps. what would be the best approach to implementing LibreQOS in this environment?

**Comment by hexatester** [comment]
You need to have two routers, with ospf running between them. And put your pppoe server at core router.
 
https://github.com/LibreQoE/LibreQoS/wiki/v1.4#network-design-assumptions

**Comment by dtaht** [comment]
Is this resolved? If not, please join us on #libreqos:matrix.org
