### ISSUE TITLE
Install Instructions DEB package points to unknown file

### ISSUE THREAD

**Issue by anthonyp-cns** [LibreQoE/LibreQoS#301]
v1.4 Install instructions points to an artifact that does not exist for the [Simple Install. ](https://github.com/LibreQoE/LibreQoS/wiki/v1.4#simple-install-via-deb-package-recommended)

**Comment by rchac** [comment]
Thanks for letting us know. The .deb is now available as part of rc5. https://github.com/LibreQoE/LibreQoS/releases
