### ISSUE TITLE
UISP integration - 'internet' topology link too dependant for tree

### ISSUE THREAD

**Issue by syadnom** [LibreQoE/LibreQoS#307]
Excuse the ambiguous title.  
Using UISP integration. 
2 sites have links in UISP to 'internet'.  
EdgeA>SiteA1>A2>A3...
EdgeB>SiteB1>B2>B3

running the integration, network.json creates 2 trees under the root.  One for EdgeA and one for EdgeB.

Site A2 does not exist in the tree from EdgeB.

This isn't desirable.  If EdgeB goes down and traffic begins to flow out EdgeA, that shaper tree and path isn't used.  EdgeB exists in EdgeA's networks.json but as a top level node.  

It would be preferrable I think for most if not all installs if the 'internet' links in UISP that are NOT at the root site are ignored.

So EdgeA would have an entire complete network tree for all sites so if traffic does end up coming in there, it's in the tree.   Same for EdgeB. 

If I remove internet links in UISP for EdgeB, then the integration builds the tree I want.   But I need those links in there because UISP wont build the map if they aren't there.  Also, the integration builds a tree starting from the internet connected (UISP's line to internet...) so deleting those 'internet' lines in UISP isn't a hack to make this work.

**Comment by rchac** [comment]
Let us know if this pull helps https://github.com/LibreQoE/LibreQoS/pull/328
