### ISSUE TITLE
UISP integration using link with less capacity

### ISSUE THREAD

**Issue by trendal** [LibreQoE/LibreQoS#334]
Tower site with 2 links to upstream tower.  UISP integrations is using the weaker link.

Link #1  60 Ghz ~1.95 Gbps capacity in UISP
Link #2  5 Ghz ~140 Mbps capacity in UISP  <-- link chosen

Both links have the "AP" on the upstream tower.

**Comment by rchac** [comment]
Should be solved with #335 If not though, please reopen. =)
