### ISSUE TITLE
UISP Integration issue with LibreQOS

### ISSUE THREAD

**Issue by gsrathore02** [LibreQoE/LibreQoS#347]
We are implementing LibreQOS in the Lab environment and facing some issues  with python related
any idea about below mentioned error?

![p9ldNR1BYKyDGesB](https://github.com/LibreQoE/LibreQoS/assets/14846250/6c22633b-f4fb-4ca3-83d6-745f3b8b5c92)

root@LibreQOS:/opt/libreqos/src# python3 integrationUISP.py
Running Python Version 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Loading Data from UISP
Traceback (most recent call last):
  File "/opt/libreqos/src/integrationUISP.py", line 486, in <module>
    importFromUISP()
  File "/opt/libreqos/src/integrationUISP.py", line 479, in importFromUISP
    case "full": buildFullGraph()
  File "/opt/libreqos/src/integrationUISP.py", line 314, in buildFullGraph
    sites = uispRequest("sites")
  File "/opt/libreqos/src/integrationUISP.py", line 22, in uispRequest
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by trendal** [comment]
That looks like it's complaining about malformed json from the uisp API.

Line 1, column 1 would lead me to believe that it's not returning anything. Maybe you have bad credentials or wrong url and the integration script isn't catching that?

**Comment by gsrathore02** [comment]
> That looks like it's complaining about malformed json from the uisp API.
> 
> Line 1, column 1 would lead me to believe that it's not returning anything. Maybe you have bad credentials or wrong url and the integration script isn't catching that?

I have resolved earlier showing credential issues (wrong token) and bad URL issues, but now I am facing the above error.

**Comment by trendal** [comment]
We have 3 instances of LibreQoS here and I'm not seeing that issue so I'm assuming it's unique to your environment.  That error message still strongly points towards an empty query result from your UISP instance. Is your UISP instance working correctly of itself?  If so I doubt that it is returning invalid JSON to LibreQoS because it uses the same API.  It would seem highly likely there is a connection error that is not getting caught in higher level error checking.

**Comment by gsrathore02** [comment]
Currently, I am working with one network card only, that issue is related to the network card? 
How can we check UISP instance working correctly ?

**Comment by trendal** [comment]
No the issue I am presuming your having is not with the network card.  

Are you able to edit the integrationUISP.py file for testing purposes or do you not have any experience in Python programming?  What needs to happen is we need to add a line in that prints out the raw data returned from the UISP API before it's sent to the JSON decoder.

Doing this via github is going to be a slow process.  There is a Matrix Chat here:  [https://app.element.io/#/room/#libreqos:matrix.org](url) where the developers and other users hang out that would be a lot quicker.  If you can't or don't want to use that then it might be advisable to connect on some other more real time messaging service to debug this. 

It appears like you have encountered a new bug that is not being handled correctly.

**Comment by gsrathore02** [comment]
> 
Thanks for response as i checked UISPBaseUrl, its showing 404 not found
Please find the below mentioned screenshot

http://192.168.6.79:8086/nms/api-docs/

![Screenshot from 2023-05-16 16-16-27](https://github.com/LibreQoE/LibreQoS/assets/14846250/19c8463b-fc47-4ea2-8f04-2a90943dc920)

**Comment by gsrathore02** [comment]
> 
Thanks for your response.

No, I am not a Python programmer. Can you please give me the troubleshooting step?
So, I can easy to solve the error.

**Comment by trendal** [comment]
On the URL that you showed there, you are using http not https.  If that is how you have the server configured that is fine, but typically it is running on a secured port with ssl.  Also I see that you are using a different port than the standard 80 or 443.  If you are getting a 404 then that is also what the integrationUISP script will be getting.  So you need to configure your UISP instance appropriately before it will work.

You should be seeing something like this when you access the api-docs

![uisp api](https://github.com/LibreQoE/LibreQoS/assets/26368339/a3bfcae6-2313-49bb-a8f1-74c83bcb32b7)

**Comment by gsrathore02** [comment]
> On the URL that you showed there, you are using http not https. If that is how you have the server configured that is fine, but typically it is running on a secured port with ssl. Also I see that you are using a different port than the standard 80 or 443. If you are getting a 404 then that is also what the integrationUISP script will be getting. So you need to configure your UISP instance appropriately before it will work.
> 
> You should be seeing something like this when you access the api-docs
> 
> ![uisp api](https://user-images.githubusercontent.com/26368339/238747735-a3bfcae6-2313-49bb-a8f1-74c83bcb32b7.png)

https://github.com/LibreQoE/LibreQoS/wiki/v1.4

in above GitHub document not mentioned SSL

and web UI is running on the below URL  as per your document.

http://SERVER_IP_ADDRESS:8086

then how can I run that application on SSL(443 port) ?

any alternative document?

**Comment by trendal** [comment]
Did you follow the install documents for UISP here?:  https://help.ui.com/hc/en-us/articles/115012196527-UISP-First-Time-Setup-Installation

**Comment by rchac** [comment]
Complete with v1.5
