### ISSUE TITLE
Splynx Topology Mapping

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#350]
Brandon Van Houten gave us some really helpful info here on how to export topology data from Splynx. Splynx apparently CAN support topology pull from API. Leaving this here to keep track of progress.

**Comment by millerchada** [comment]
Looking to see if there has been any more work done on this?  Or if it hasn't if you can share the API info that was pointed out to get the topology information.  This is something that we would really be able to benefit from and I would like to help wherever I can with this.

**Comment by brandon24031** [comment]
Good day,

I got this code from ChatGPT obviously I am not a programmer but the code looks like it makes sense to pull network topology from the Splynx tree.

import requests
import json

# Splynx API endpoint URL
api_url = 'https://your-splynx-instance/api/v1/'

# API credentials
api_username = 'your-username'
api_password = 'your-password'

# API request headers
headers = {
    'Content-Type': 'application/json',
    'Accept': 'application/json'
}

# Authenticate and obtain API access token
auth_data = {
    'username': api_username,
    'password': api_password
}

auth_response = requests.post(api_url + 'auth', headers=headers, json=auth_data)
auth_json = auth_response.json()

if 'access_token' in auth_json:
    access_token = auth_json['access_token']
    headers['Authorization'] = 'Bearer ' + access_token
else:
    print('Failed to authenticate with Splynx API.')
    exit()

# Fetch network topology data
topology_url = api_url + 'network-topology'
topology_response = requests.get(topology_url, headers=headers)

if topology_response.status_code == 200:
    topology_data = topology_response.json()

    # Process and print the network topology
    if 'data' in topology_data:
        for node in topology_data['data']:
            print('Node ID:', node['id'])
            print('Node Name:', node['name'])
            print('Node Type:', node['type'])
            print('---')
    else:
        print('No network topology data found.')
else:
    print('Failed to fetch network topology from Splynx API.')



Regards,

Brandon Van Houten
***@***.***

**Comment by millerchada** [comment]
Robert,
  I should be back in the office tomorrow and will try and open a ticket
with them. I’ll let you know what I find out.

-Chad

**Comment by rchac** [comment]
Complete with v1.5
