### ISSUE TITLE
Exclude certain specified IPs from RTT tracking (UISP)

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#352]

**Comment by thebracket** [comment]
We'll have to do some testing to see what the performance impact of doing another test on a map to see if it should be excluded is. I think it'll be pretty light.

**Comment by thebracket** [comment]
We have the ability to do this now, but I think we forgot to include it in the UI!

**Comment by rchac** [comment]
Fixed. There's now an optional ```do_not_track_subnets``` field that excludes flows from tracking if they are in there.
