### ISSUE TITLE
Validate network 

### ISSUE THREAD

**Issue by jaber-the-great** [LibreQoE/LibreQoS#374]
Hi,
I was checking the LibreQoS.py code and I came across the issue with validating network. 
1. Line 259: 
if (devicesValidatedOrNot == True) and (devicesValidatedOrNot == True): 
should be change to:
if (devicesValidatedOrNot == True) and (networkValidatedOrNot == True): 

2. The is no validation check for network.json:
networkValidateOrNot is set true in line 126

networkValidateOrNot is just written in a line of code without having a value assigned to it in line 143(I guess you meant to make it false when we can not open the network.json file, but there is no assignment to that). Also, for consistency, if the network validation is not passed, it is better to have the relevant message printed: "network.json failed validation""
Line 144 checks the value networkValidatedOrNot is true or not, and if true, printing "network.json passed validation" 

Beside fixing line 259 and 143, is it the case that we only want to validate there is a file called network.json with read access or we need to perform other validation similar to verifying shapedDevices.csv?

**Comment by rchac** [comment]
@jaber-the-great Thank you for noticing this and pointing it out. I have attempted to resolve these issues with [this PR](https://github.com/LibreQoE/LibreQoS/pull/378/commits/0d766109541eb3a113fd524efe8ff90aa206e50b). Please let me know if I missed anything.

**Comment by jaber-the-great** [comment]
I was about to fix this issue :)
I was going to talk to you about the criteria for validating the network. 
One criteria can be the type of devices we have. Considering the hierarchical relationships between sites, PoP and access point, the parent/children relationship should be checked here or when creating the node using addRawNode. 
What do you think about it?
I think simply editing the addRawNode is better. I can go ahead and fix the issue if you also think it is valid.
