### ISSUE TITLE
PoP node type

### ISSUE THREAD

**Issue by jaber-the-great** [LibreQoE/LibreQoS#379]
There is No PoP node type in IntegratoinCommon.py but in the INTEGRATION_HOWTO.md, it is introduced as a node type. 
Either the INTEGRATION_HOWTO.md should be updated or the new node_type: PoP should be added to the integrationCommon.py. 
By the way, I'm not sure about the usage of PoP since it can be categorized as site. 
In any case, I can fix it and make a pull request.

**Comment by thebracket** [comment]
I'd be inclined to fix the documentation - sites and PoPs are the same
thing, unless I'm missing something?

**Comment by jaber-the-great** [comment]
That's a good Idea. I can go ahead and fix it.
