### ISSUE TITLE
Got disconnect after installed

### ISSUE THREAD

**Issue by ilhay** [LibreQoE/LibreQoS#396]
OS: Ubuntu 22.04 LTS
Kernel: 5.15
Mainboard: Supermicro H12SSL-i (latest BIOS & BMC Firmware)
NIC: MCX512A-ACAT

I follow a process to install LibreQOS and then I finish to run 'apt install libreqos'. Server is connected and cannot remote or access web UI.

![ss-224548-CXUtqOl](https://github.com/LibreQoE/LibreQoS/assets/5000075/a2a97d52-8992-48d5-adf8-bc0b9355d668)

![ss-224648-HDgwo2V](https://github.com/LibreQoE/LibreQoS/assets/5000075/1273da57-e3c8-4c3e-a32d-1657029027b0)

Any ideas what I do missing?

Thank you.

**Comment by thebracket** [comment]
The problem is `bond0`. LibreQoS doesn't support bonded interfaces (they don't have XDP support).
