### ISSUE TITLE
Bug in Max upload and download rate (for shaped device and ispConfig)

### ISSUE THREAD

**Issue by jaber-the-great** [LibreQoE/LibreQoS#397]
Hi, 
The tcpOverheadFactor = 1.0 and bandwidthOverheadFactor = 1.0. 
But libreqos web interface and my throughput measurements show values which are a little bit more than the defined Max upload and Max download for the shaped device. The difference is more than that we can say it's due to considering K as 1000 or 1024. 
For example, for for 3Mbps max uplaod/downlaod, I observed values like 4.7Mpbs and 5Mpbs in LibreQoS web interface or iperf3 showed 3.16Mbps.
Or  for Download min = 2Mbps and Download max = 8Mbps , I observed several instance of: 8.17Mbps, 8.32Mbps, 8.1Mbps etc. 
I saw these values both on LibreQoS web interface and iperf3 verbose and speedtest-cli result.

**Comment by dtaht** [comment]
I too would prefer specifying in binary mbit rather than decimal.

**Comment by jaber-the-great** [comment]
After talking with my colabs about this issues, I realized the speedtest/iperf3 and other bandwidth measurement tools are not precise. The other thing is that we use tc for shaping the traffic and tc is not precise too (I'm not sure about this part, one of my friends working on network measurement shared his experience with me)

**Comment by jaber-the-great** [comment]
It can also happen since the DRR in fq_codel let the traffic goes through the network if there is leq 1MTU data in the queue.

**Comment by dtaht** [comment]
btw, thx for closing more bugs than you opened today. :)

**Comment by jaber-the-great** [comment]
Lol.
________________________________
