### ISSUE TITLE
LibreQoS & Layer3 (routed)

### ISSUE THREAD

**Issue by Belyivulk** [LibreQoE/LibreQoS#41]
Hi Fam,

We've started investigating the possibility of running LibreQoS with routing rather than bridging. 

So far, atleast in testing it "kind of works". For reasons that are unclear to us just yet it "sometimes" does not want to shape upload traffic (from user -> internet). It always shapes download (internet -> user). 

Is there any obvious reason we've missed as to why routing would not work correctly all the time in the upload direction, but always works correctly in bridged mode? 

Thanks fam!

**Comment by rchac** [comment]
Is it possible that the dst and src addresses of the packets aren't matching the hosts intended to be shaped? Libre matches based on the src and dst host of each packet, so if you do shaping upstream of NAT, it could get confused.

**Comment by Belyivulk** [comment]
If that were the case it wouldn't work correctly in bridge either (i'd have thought). I don't think there is any NAT involved, but will need to check that.

From where you stand though, a pure routed set up should work same as bridged?

**Comment by rchac** [comment]
Assuming you mean where the routers upstream and downstream of libreqos are routing between each-other - thats perfectly fine, and probably ideal. that's how I use it in production and it works well. If you have time youre welcome to illustrate your current setup for us to better understand. A template Draw.io diagram is available [here](https://github.com/rchac/LibreQoS/blob/main/docs/diagram.drawio).

**Comment by Belyivulk** [comment]
Yeap; thats what i mean. Will crack on with a diagram a bit later today. 

Generally what we're seeing (and we dont understand why) is that testing from a client to a host we control within our network shapes perfectly fine (with Libre doing the shaping), all the time.

The moment we run through our edge (to external hosts) generally the first upload test will shape fine at 6mbit (the value we're using); then the second appears to not shape at all. Further tests continue to shape the upload traffic perfectly fine to those internal hosts; but externally not at all. Download traffic appears to always be shaped, perfectly fine. 

We're now down to only one host (customer) traversing the box and static routes (to ensure the traffic is always traversing the correct path).

Its a bit of a mystery at the moment!

**Comment by rchac** [comment]
are you using OSPF between the upstream and downstream router? If so - are the two links ECMP or does the LibreQoS path have a lower cost?

**Comment by Belyivulk** [comment]
We started off with BGP and differing paths. We're now down to single path / single user / static routes. I can see the traffic traversing the correct interfaces (and we've packet captured as well). From that perspective it all *looks* okay. The thing thats really throwing us is that it works fine, everytime, to hosts within our network. It works fine everytime in bridged. It only flakes when routing and external hosts, and even then only one the second or third test (and only in the upload direction).

**Comment by rchac** [comment]
i suspect it's something to do with src/dst address on each packet, or that the route for some traffic is going around the LibreQoS box

**Comment by Belyivulk** [comment]
We'll dig a bit deeper. 

Just to make sure i've got this right; your own set up does not have a bridge on the Libre box; you route in/out of it and/or have it participating in BGP directly?

**Comment by rchac** [comment]
In my setup, the router upstream and downstream of the LibreQoS box route to eachother via OSPF. LibreQoS uses bridge br0 to intercept traffic passing between the two routers over a low-cost path. My setup follows [this diagram](https://raw.githubusercontent.com/rchac/LibreQoS/main/docs/design.png). In my setup, the LibreQoS box has no knowledge of the routes or routing protocols, because it's not needed.

I would not recommend to have the LibreQoS participate in BGP or have any routing happening on that box directly.

**Comment by Belyivulk** [comment]
Thanks for the explanation and that is what we had (and does work fine) as well (except BGP, not OSPF). So when i say bridging, this is the set up I refer to.

Aside from overhead; why would you not have LibreQoS participate in routing on the box directly? For us it is potentially desirable in order to overcome some other issues associated with the bridged design.

Thanks for all your help!

**Comment by rchac** [comment]
> Aside from overhead; why would you not have LibreQoS participate in routing on the box directly? For us it is potentially desirable in order to overcome some other issues associated with the bridged design.

I'm not 100% familiar with the [linux routing flow](https://inai.de/images/nf-packet-flow.svg) (it's a lot), but I think introduce routing protocols on the LibreQoS box could lead to packets routing in unintended ways.

**Comment by interduo** [comment]
@Belyivulk did You success in using L3 as only one network card configuration?

**Comment by Belyivulk** [comment]
Sadly no :(

**Comment by interduo** [comment]
@Belyivulk
could You show:
```
tc qdisc show
tc class show
tc filter show
ip a s
ip r s
iptables -t nat -L -n
```

**Comment by Belyivulk** [comment]
In which mode? As it stands we're bridging through..is that the data you want?

**Comment by interduo** [comment]
Have You got L3 testing instance nearby?

**Comment by Belyivulk** [comment]
I want to be clear; as it stands we route through the LibreQoS "box" but it does not participate in routing (and this works)

When we try to get it to participate in routing; it fails. 

As it stands its a half hours work to test "L3" (participation in routing) as we know it :) 

So...

**Comment by dtaht** [comment]
See: #153

**Comment by dtaht** [comment]
wont fix. we are a bridge for the concieveable future.
