### ISSUE TITLE
UISP Integration TypeError: string indices must be integers 

### ISSUE THREAD

**Issue by AwesomePilot828** [LibreQoE/LibreQoS#413]
When running python3 integrationUISP.py  the following error is returned.

Loading Data from UISP
Traceback (most recent call last):
  File "/opt/libreqos/src/integrationUISP.py", line 486, in <module>
    importFromUISP()
  File "/opt/libreqos/src/integrationUISP.py", line 479, in importFromUISP
    case "full": buildFullGraph()
  File "/opt/libreqos/src/integrationUISP.py", line 319, in buildFullGraph
    sites, dataLinks, uispSite = handleMultipleInternetNodes(sites, dataLinks, uispSite)
  File "/opt/libreqos/src/integrationUISP.py", line 287, in handleMultipleInternetNodes
    if link['canDelete'] ==  False:
TypeError: string indices must be integers

Running version 1.4

**Comment by rchac** [comment]
What UISP version are you running?

**Comment by AwesomePilot828** [comment]
UISP Version is 1.6.5

**Comment by rchac** [comment]
Looks like the older UISP version is the culprit. As a workaround, try setting ```uispSite = "YOUR_ROOT_SITE"``` in ispConfig.py, replacing YOUR_ROOT_SITE with whatever the exact name of your root site is in UISP.

**Comment by AwesomePilot828** [comment]
Thanks for the suggestion!   I will try this and report back next week when I get back to the machine I'm setting up.  

I have considered upgrading UISP, but sometimes the new versions aren't ready for primetime... So I keep putting it off waiting for good feedback from the community.   

I'll report back early next week.

Thanks!

**Comment by rchac** [comment]
Complete with v1.5
