### ISSUE TITLE
Add ability to use VictoriaMetrics instead of InfluxDB for long-term stats

### ISSUE THREAD

**Issue by valyala** [LibreQoE/LibreQoS#430]
It would be great if LibreQoS could be able to use [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) instead of InfluxDB for long-term stats. VictoriaMetrics [can accept data in Influx line protocol](https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf). It usually requires lower amounts of RAM and disk space than InfluxDB.  It runs and scales smoothly on any hardware starting from  Raspberry PI (see [HomeAssistant case](https://community.home-assistant.io/t/victoriametrics-add-on-for-long-term-storage-and-data-source-for-grafana/466197)) and ending with hosts containing hundreds of CPU cores (see [this case](https://docs.victoriametrics.com/CaseStudies.html#wixcom)).

VictoriaMetrics doesn't support Influx query language, but it supports Prometheus query language (PromQL and [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html)) and Graphite query language - see [how to use Prometheus-compatible querying API](https://docs.victoriametrics.com/#prometheus-querying-api-usage) and [how to use Graphite querying API](https://docs.victoriametrics.com/#graphite-api-usage).

P.S. it would be great if LibreQoS would provide long-term stats out of the box without the need to install optional third-party solutions such as InfluxDB or VictoriaMetrics. For example, it shouldn't be too hard to embed VictoriaMetrics into LibreQoS, since it is a relatively small (20MB) statically linked binary without external dependencies, and it requires low amounts of CPU, RAM and disk space under low load.

**Comment by rchac** [comment]
More info about our Long Term Stats service here: https://libreqos.io/lts/
