### ISSUE TITLE
Very high cpu usage on one core

### ISSUE THREAD

**Issue by arm946ejs** [LibreQoE/LibreQoS#447]
Runing libreqos 1.4 on ubuntu 22.04.3 with XDP bridge. I got very high cpu usage on one core. Nearly 100% @ 800Mbps downloading. Load balance not working at all. System build up with J4125 and Mellanox cx4 lx. I can see XPD ids from  "ip a" shell command. I don't  know what is going on. I build another system with different NIC which is intel x520  and they all have the same problem.
Here is the log and test result. 
![Snipaste_2023-12-28_15-59-40](https://github.com/LibreQoE/LibreQoS/assets/21214321/72c1f59a-1dc8-42b8-96ed-17a7b684b441)
![Snipaste_2023-12-28_15-45-51](https://github.com/LibreQoE/LibreQoS/assets/21214321/a54292d1-6a32-4778-a0e6-5fff5b7044bb)
[log.txt](https://github.com/LibreQoE/LibreQoS/files/13784388/log.txt)

**Comment by thebracket** [comment]
It sounds like your network.json is concentrating the majority of your
traffic on one CPU. Maybe try a "flat" topology? That should divide the
load equally. (The worst case is if you have a top level node, a node
beneath it and everything under that - that will cram everything onto one
CPU).

What CPU are you using? I'm surprised you aren't getting a bit more on a
single core. (Unless hyper threading is enabled and it unluckily picked an
HT virtual core, or you are in a VM - both of those hit performance
terribly)

**Comment by arm946ejs** [comment]
Dear thebracket:
     Thank you for your reply.  I did a new test using the following configuration file.  By using a flat topology.  There is still a single core full loading situation and this time the load goes form core 0 to core 1.
I tried to install the Mellanox official network card driver but there is no difference. I recknized that the count of system  local interrupt is very high on core 0. cpumap thread take a lot of resource. Maybe this is the proble.

My system uses intel J4125  4 cores low-power CPU  without hyper threading. Bare-metal runing Ubuntu system. All pcie lans comes from PCH.







thanks!



***@***.***
 
From: thebracket
Date: 2023-12-29 10:28
To: LibreQoE/LibreQoS
CC: arm946ejs; Author
Subject: Re: [LibreQoE/LibreQoS] Very high cpu usage on one core (Issue #447)
It sounds like your network.json is concentrating the majority of your 
traffic on one CPU. Maybe try a "flat" topology? That should divide the 
load equally. (The worst case is if you have a top level node, a node 
beneath it and everything under that - that will cram everything onto one 
CPU). 

What CPU are you using? I'm surprised you aren't getting a bit more on a 
single core. (Unless hyper threading is enabled and it unluckily picked an 
HT virtual core, or you are in a VM - both of those hit performance 
terribly)

**Comment by rchac** [comment]
@arm946ejs your Intel J4125 has a very low passmark single-thread score (1166), and is not a good choice for delivering plans above 100 Mbps. You need a system with a CPU that has a higher single-thread passmark score. https://libreqos.readthedocs.io/en/latest/docs/SystemRequirements/Compute.html

Our estimates were that a CPU like the Intel J4125 would only be capable of queuing 100 Mbps plans, so it is actually quite surprising to see one passing 800 Mbps on a single CPU.

You'll want to consider a more powerful system such as the ones listed here https://libreqos.readthedocs.io/en/latest/docs/SystemRequirements/Compute.html#server-recommendations
