### ISSUE TITLE
[Libreqos 1.5] failing build - any ideas?

### ISSUE THREAD

**Issue by khandieyea** [LibreQoE/LibreQoS#477]
Hey guys,

I just attempted a built from the `develop` aka "1.5" branch, following [these instructions](https://github.com/LibreQoE/LibreQoS/blob/main/docs/v1.5/TechnicalDocs/git-install.md)

At `./build_rust.sh`, hit the following

![image](https://github.com/LibreQoE/LibreQoS/assets/911315/df3d9d38-1f2e-46a9-a14f-ff57c1875a23)

Mostly followed the letter to  a t, with a few nuances/caveats, listed below with other notes

The box is running Ubuntu 22.04 (22.04.1 LTS)
Kernel 5.15.0-88
This host was/is running libreqos 1.4 already, which I just stopped the systemd tasks

- Installed libreqos into `/opt/libreqos15` - in case that makes a difference?
- Using latest commit on `develop` branch -  `9ba992db5f1c12b9661bccf8bd7b4779f0d9d174`
- Upgraded python to 3.11 from 3.10
- Upgraded pip to 24 from 22
  - pip22 did not support `--break-system-packages`
  - nb: pip24 required `-r` to read from `requirements.txt` correctly.
- Regarding `sudo cp /usr/lib/x86_64-linux-gnu/libpython3.11.so /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0`
  - There wasn't a `libpython3.11.so`
  - However, `libpython3.10.so.1.0` already existed
  - Default/vanilla rust install, rustup is v1.27.0
  
  Any help is much appreciated, I am happy to provide more detail - whatever is useful
  
  Thanks :smile:

**Comment by rchac** [comment]
As it states in the error, libpython3.11 is missing. Do `sudo cp /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0 /usr/lib/x86_64-linux-gnu/libpython3.11.so `

**Comment by khandieyea** [comment]
Hey Robert, Thanks for that. I will retry the build tomorrow. Thanks :)
