### ISSUE TITLE
v1.5-beta: version numbering not from VERSION_STRING

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#507]
Very small thing:

Here:
https://github.com/LibreQoE/LibreQoS/blob/f82981ecd7c52838dfb748f0c31a76e7f558f090/src/rust/lqos_setup/src/main.rs#L227

There is no version gathered from VERSION_STRING file.

**Comment by thebracket** [comment]
The setup assistant needs some love/updating in general - but good catch.

**Comment by interduo** [comment]
![image](https://github.com/LibreQoE/LibreQoS/assets/17087236/c8ddb180-6c54-4085-8be1-49f5b050ee69)
look at UI at footer - there one more catch

**Comment by thebracket** [comment]
This is fixed in the UI2/develop branches.
