### ISSUE TITLE
v1.5-beta (package from download link: libreqos_1.5.202406251802-1_amd64.deb for ubuntu22.04 - libpython3.10, build_dpkg.sh got some missed/broken check or no dependancy check,

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#508]
I installed a libreqos for testing purposes using download link from form and deb package libreqos_1.5.202406251802-1_amd64.deb.

After instalation I tried to run:
```
root@libreqos-beta:/opt/libreqos/src/bin# ./lqosd 
./lqosd: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory
```
Simply check:
```
root@libreqos-beta:/opt/libreqos/src/bin# ldd lqosd
	linux-vdso.so.1 (0x00007ffff63e1000)
	libelf.so.1 => /lib/x86_64-linux-gnu/libelf.so.1 (0x0000712a26b67000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x0000712a26b4b000)
	libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x0000712a26aa1000)
	libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x0000712a25a00000)
	libpython3.10.so.1.0 => not found
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x0000712a26a72000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x0000712a25f17000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000712a25600000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x0000712a25946000)
	/lib64/ld-linux-x86-64.so.2 (0x0000712a26b8d000)
```
It suggests that build_dpkg.sh got some missed/broken check or broken/no dependancy check.
I see when `bash -x ./build_dpkg.sh` that ldd screams with error 

Temporary workaround for this:
```
find / -name "libpython3*so"
/usr/lib/x86_64-linux-gnu/libpython3.12.so
/usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12.so
```

`ln -s /usr/lib/x86_64-linux-gnu/libpython3.12.so.1.0 /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0`

**Comment by thebracket** [comment]
There's a fix for this in the new `build_dpkg.sh` that hasn't shipped yet. 

https://github.com/LibreQoE/LibreQoS/commit/68abb2b5b422211f798bd91d8e619fca90448112
https://github.com/LibreQoE/LibreQoS/commit/dbd1b6b46dd59cefa3088374611990800e02d4ce

It's similar - it scans `lqosd` with `ldd`, and then looks for an alternative `libpython` to connect to.

**Comment by interduo** [comment]
Ohhhh i even little inprovey that code range. So after rebuild of deb package this issue could be closed. Probably  -beta2?

**Comment by interduo** [comment]
Checked again that on newest state of develop branch, it's not existing anymore. So I close this. Thanks for tagging.
