### ISSUE TITLE
Safeguard for running many simultaneus LibreQoS.py

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#52]
LibreQoS needs safeguard for running many simultaneus `LibreQoS.py` this is important because many technicans can use CRM and add/change/delete QoS classes. We will do this in CRM integration lvl - but it's should be done here also.

I see this like:
1. `LibreQoS.py --force-refresh-shapers` (without parameters just prints the rules on stdoutput)
2. hardcode that check in code (and ommit this when --force-refresh-shapers is set),
3. API calls should also got some safeguard or queue,

I saw the `enableActualShellCommands` variable in ispConfig.py but when I set this I cannot pass all the things to XDP.

**Comment by dtaht** [comment]
Yes, multi-user behavior, is, in general, a problem throughout libreqos. It would be able to insert, update and delete customers dynamically without affecting the whole system. The hope is, however, by making this open source, that individual contributors will have good ideas, do a fork, implement their favorite feature, and do a pull request. 

There presently is not a whole lot of top down direction, however given the uptick of interest in it recently, pulling together 
a meeting of as many of the users as possible to discuss various pain points like these, is increasingly on my mind.

**Comment by interduo** [comment]
As a fast workaround:
run `LibreQoS.py` with bash script with `flock` or `lockfile` command inside this wrapper.

**Comment by dtaht** [comment]
This locking thing still a thing?

**Comment by interduo** [comment]
Yes.

**Comment by dtaht** [comment]
@rchac This locking thing still a thing?

**Comment by thebracket** [comment]
I'd like to add a lock to lqosd for the same reason - avoid getting into
bizarre states.

The corollary: include some advice on removing stale locks after an an
unexpected restart.

**Comment by rchac** [comment]
> The corollary: include some advice on removing stale locks after an an
unexpected restart.

This is something I want to be sure I do correctly on the python side. Any recommendations here to account for unexpected reboots?

**Comment by interduo** [comment]
Maybe that way:
Every run of libreqos should generate some ID. 
We should do some "lock" in RAM. 
There would be no problem after reboot of machine/VM.
?

**Comment by dtaht** [comment]
I think it would be good to retire ispConfig.py, in favor of moving those vars to and reading the toml and using this locking method also in the python. @rchac ?

**Comment by interduo** [comment]
Maybe a good way is to use systemd service files for all critical commands? And puuuuf the problem would gone. 
@rchac what do You think about it?

**Comment by dtaht** [comment]
There is more than one way to do it. Other OSes still do not use systemd. The lockfile method does work in more cases.

**Comment by rchac** [comment]
@dtaht Would binding to a port be a reasonable solution? https://stackoverflow.com/a/63525705

**Comment by interduo** [comment]
No because some actions could be run on multiinstance like getting statistics.

**Comment by dtaht** [comment]
The traditional way is the lockfile on a temporary filesystem, with the pid in it. 

dtaht@tank:~/git$ df /var/run/
Filesystem     1K-blocks  Used Available Use% Mounted on
tmpfs            1331052   196   1330856   1% /run

**Comment by interduo** [comment]
Ok - so we need to get back lqos_tools.py and move functions for printing statistics for IPs or just move that to rust to 'ask the lqosd bus'.

**Comment by rchac** [comment]
Stats gathering is outside of LibreQoS.py though. It's handled by scheduler.py and in turn graphInfluxDB.py

**Comment by rchac** [comment]
@interduo Ah ok. Here's a modernized lqTools.py. It probably won't work with OnAStick mode quite yet but I tested with v1.4 and XDP bridge and it works. :) https://github.com/LibreQoE/LibreQoS/blob/main/src/lqTools.py

**Comment by thebracket** [comment]
The last commit adds file locking to the Python process.
