### ISSUE TITLE
How to update from 1.4 to 1.5 latest beta if installed using APT?

### ISSUE THREAD

**Issue by owaismai** [LibreQoE/LibreQoS#540]
There does not seem to be a LibreQoS APT repository for the beta version. How should I upgrade to the latest beta (very excited, just saw the video now about the new UI)
Would I have to remove it and install via git?

**Comment by thebracket** [comment]
The new UI will be in beta 2, which isn't packaged quite yet. When it is,
we'll distribute via the website (LibreQoS.io). It shouldn't be long now.

(You can get it by building the develop branch from source)

**Comment by owaismai** [comment]
Perfect. Thanks. As of writing, the beta 2 is packaged as a deb. So downloading it and simply installing it by doing **dpkg -i file.deb** works 100%
