### ISSUE TITLE
Dashboard does not show behind Caddy reverse proxy

### ISSUE THREAD

**Issue by owaismai** [LibreQoE/LibreQoS#542]
Ver: lqos Beta 2
Caddy v 2.8.4

Issue:
All set up and i can reach the dashboard using caddy. But the dashboard does not show. 
**Tree** shows but does not auto update
**Tree overview** works and auto updates 

my caddyfile:
```

example.com {
        # Set this path to your site's directory
        root * /usr/share/caddy

        # Enable the static file server
        file_server

        # Reverse proxy for LibreQoS
        reverse_proxy /lqos/* http://<IP_ADDRESS>:9123

        # Reverse proxy for InfluxDB
        reverse_proxy /influxdb/* http://<IP_ADDRESS>:8086

        # Enable TLS with on-demand certificates
        tls {
                on_demand
        }
}

lqos.example.com {
        reverse_proxy <IP_ADDRESS>:9123

        # Enable TLS with on-demand certificates
        tls {
                on_demand
        }
}

id.example.com {
        reverse_proxy http://<IP_ADDRESS>:8086
}

```

**Comment by thebracket** [comment]
I'm out of town for the week - are you trying to add https, or just proxy
in general? For just reverse proxy, you'll need to support a couple of
Websocket URLs with upgrade (I'll have to get to a computer larger than my
phone to get them). If you're seeking https, we'd also need to add a couple
of lines to the JavaScript (to detect the URL, and use wss:// as opposed to
ws:/ ).

(Not very familiar with Caddy, I tend to go with nginx)

**Comment by thebracket** [comment]
I think commit 26c3269 should take care of this (and lists the URLs). I'll get it into a draft PR - I can't test it until I'm back home.

**Comment by thebracket** [comment]
Ok, PR #543 should stop us from forgetting this - I think it works, but haven't been able to test yet.

**Comment by rchac** [comment]
Cannot reproduce, but will reopen if desired
