### ISSUE TITLE
Possible memory leak v1.5-beta-2

### ISSUE THREAD

**Issue by rchac** [LibreQoE/LibreQoS#548]
<img width="989" alt="image" src="https://github.com/user-attachments/assets/6004432a-da20-4d77-959a-7d4a683972e0">

**Comment by thebracket** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🛶 Memory is Leaking](https://trello.com/c/4lOhhCwZ/2-%F0%9F%9B%B6-memory-is-leaking)

**Comment by rchac** [comment]
Fixed in v1.5-Beta3
