### ISSUE TITLE
Debian 12 not compile

### ISSUE THREAD

**Issue by manchelsi** [LibreQoE/LibreQoS#577]
How can I compile under Debian 12? Any attempts fail.

**Comment by FrantisekBorsik** [comment]
We really recommend and even require people to use Ubuntu:  "Linux kernel 5.11 or greater is required, as 5.11 includes some important XDP patches. Ubuntu Server 22.04 uses kernel 5.13, which meets that requirement."
https://libreqos.readthedocs.io/en/latest/docs/v1.5/Quickstart/quickstart-prereq.html

**Comment by manchelsi** [comment]
Got it, thanks.
