### ISSUE TITLE
Qdisc Processing Offloading to Server iGPUs

### ISSUE THREAD

**Issue by cherusk** [LibreQoE/LibreQoS#585]
Pardon me, I do not want to abuse the "Issues" of this repo for that is not necessarily one. Yet its more efficient than to raise this than via the other channels. Not sure if the bufferbloat mailing lists are still active. Cue me to where to raise this if inappropriate here please.

Might consider this as a feature proposal.

There was prior work done on integrating iGPUs of Server CPUs in network stack processing. [1]

As many processing steps of the queue discipline can be batched to an iGPU, especially those with little branching, e.g. flow hashing. That might be a quicker engineering way to reducing the CPU footprint than to await the next iteration of SMART-NICs.

iGPU seem most interesting, because those do not necessarily incur a dispatching overhead to a CPU detatched  GPU via some form of a bus and back. iGPUs can essentially process on memory like usual CPU cores do.

Huge drawback might be, that not necessarily that many server level CPUs have an integrated iGPU.

The authors report of accelerations for network stack processing of sub-decimal factor(2 to 4), that sounds little, but can be significant enough to make a deployment more viable in high bandwidth link scenarios. Depending on implementations, the acceleration might exceeded that. Imagine instead of the need for a 64 core cpu to only need one with 10 - 20 cores CPU with an iGPU included. That's an argument if you asked me.

Bringing this up, because I did not hear you mention works done in that direction in the related discussion here [2].

[1]
https://ieeexplore.ieee.org/document/7502464

Caused by/Related To:
[2] https://github.com/LibreQoE/LibreQoS/issues/578

**Comment by thebracket** [comment]
With the current LibreQoS implementation using Linux's TC for qdisc processing, this would be better targeted at the Linux kernel developers. If we eventually go for a full bypass solution (DPDK, AF_XDP, etc.) then something like that may be viable.

**Comment by cherusk** [comment]
@thebracket ok thank you for the reply. Closing hence.
