### ISSUE TITLE
Monitoring LibreQOS

### ISSUE THREAD

**Issue by convergedmw** [LibreQoE/LibreQoS#6]
Please advise if there is a way to monitor LibreQOS via a tool like LibreNMS or CheckMK? We have it nicely running inside our network and now I'd like to get our NOC to keep an eye on it...

**Comment by rchac** [comment]
Hello. I can definitely try my hand at it. Perhaps an SNMP interface so LibreNMS can graph it? What stats would you like to see on the monitoring? Thanks, Robert

**Comment by convergedmw** [comment]
One very useful report would be what IPs are passing through under what HTB. And also if there are any IPs that haven’t been “provisioned” into a service level Sort of like a mapping of the Shaper.yaml against life traffic. Showing which IPs are “live” (passing traffic), and under which Site/AP they’re configuredBrian Longwe | CEO | Converged Technology Networks+265999708883 | https://www.ctnmw.net | Twitter: blongweOn Sat, 22 Jan 2022 at 2:19 AM Robert wrote:
Hello. I can definitely try my hand at it. Perhaps an SNMP interface so LibreNMS can graph it? What stats would you like to see on the monitoring? Thanks, Robert

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/rchac/LibreQoS/issues/6#issuecomment-1018987432",
"url": "https://github.com/rchac/LibreQoS/issues/6#issuecomment-1018987432",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by syadnom** [comment]
What would be great is to extract the latency details (direct blow at preseem's measurements) to see TCP stats for customers.

throughput per site, per AP, per customer, per customer IP.

I would rather see this exported to a time series db like influx or promethius than via SNMP.   That would expose the data to native and existing integrations with grafana and chart.js etc.

**Comment by rchac** [comment]
> What would be great is to extract the latency details (direct blow at preseem's measurements) to see TCP stats for customers.
> 
> throughput per site, per AP, per customer, per customer IP.
> 
> I would rather see this exported to a time series db like influx or promethius than via SNMP. That would expose the data to native and existing integrations with grafana and chart.js etc.

Here is a sneak preview of v1.1
![Preview](docs/v1.1-alpha-preview.jpg "Preview")

**Comment by rchac** [comment]
Thank you for the suggestion. Right now it breaks it down by AP (lowest level parent node) but I will think up how to display graphs by sites so tracking backhaul utilization is easier.

**Comment by syadnom** [comment]
excuse me... SITE NAME...

**Comment by interduo** [comment]
https://github.com/rchac/LibreQoS/issues/75 <--- I didn't find this issue earlier so I made duplicate and I describe there how I see this case.

**Comment by dtaht** [comment]
I would like us to use this quote in the press release:

"wha?!?!?!?! dude, this is incredible."

**Comment by dtaht** [comment]
otherwise, closing.
