### ISSUE TITLE
don't busy CPU with graphs and other things

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#74]
Consider:
- leaving first two cores empty (set by variable eg. useCpuCoresCount: 2-19) for not used by TC. InfluxDB and many other things could be aimed on that cores,
- setting systemd `CPUAffinity` to empty cores (eg 0-1),

**Comment by interduo** [comment]
For first we could ommit autodetection of rx/tx queues in LibreQoS.py and set the staticnumber of queues here:
https://github.com/rchac/LibreQoS/blob/main/v1.2/LibreQoS.py#L76-L97

**Comment by rchac** [comment]
Because of how xdp-cpumap-tc works (it assumes first x cores), it may be best to limit queuesAvailable by -1 and set the InfluxDB CPUaffinity to the last core. My struggle has been figuring out how to turn off multi-threading in InfluxDB. Do you happen to know how? Once I know how to do that we can set CPU affinity for influxdb.

**Comment by interduo** [comment]
Have You tried to set CPUAffinity in InfluxDB service?

Maybe instead of setting separetly all the services just set CPUAffinity in `/etc/systemd/system.conf` to last cores instead of first as I said earlier.

**Comment by rchac** [comment]
How cool, I wouldn't have guessed that would be possible. That's a nicer way to achieve it. I will experiment with that later this evening after work to make sure InfluxDB "sticks" to the chosen core range. If so, either approach (influxdb to last cores, all processes besides XDP to last cores) should be great.

**Comment by interduo** [comment]
**It's better to work together than alone.**

All the issues I posted here we "repair" at ours 8y+ scratch HFSC scripts it costs us so much time in past to find the right solution. It would be a stupidity to resolve those kind of cases again one more time.

If someday LibreQoS will support NAT then I will come with new bag of corner-cases, tips, tests and researches.

**Comment by rchac** [comment]
I completely agree. Very much appreciate your contributions to improve LibreQoS based on your teams experience and lessons learned. Queuing in Linux is poorly understood and hard for new operators to tackle, so I hope with this project we can make the benefits of QoE/QoS available to small ISPs around the world. It saves all of us time and effort, and helps us all to be competitive.

**Comment by rchac** [comment]
So I edited
```
sudo nano /etc/systemd/system/influxd.service
```
adding
```CPUAffinity=15```
then ran
```
sudo systemctl daemon-reload
sudo systemctl restart influxd
```
And it works. InfluxDB only ran on the assigned core. However, surprisingly, influxdb only spiked to 2% of the assigned CPU core on each run of graphBandwidth.py. InfluxDB's CPU usage may not be a cause for concern.

**Comment by interduo** [comment]
Could we set MAX_CPUS used in `xdp_redirect_cpu_kern` from variable in ispConfig.py ?

**Comment by rchac** [comment]
Note - added to ispConfig.py for v1.2+
```
# Allows overriding queues / CPU cores used. When set to 0, the max possible queues / CPU cores are utilized. Please leave as 0.
queuesAvailableOverride = 0
```

**Comment by dtaht** [comment]
@interduo - I would enjoy a chance to chat with you via videoconference soon.

**Comment by interduo** [comment]
I am available everyday from beginnig week - please write me day earlier.

**Comment by rchac** [comment]
Our recommendation: Run InfluxDB on VM of separate networked machine or use queuesAvailableOverride and pin InfluxDB to last core
