### ISSUE TITLE
Mark and view packets in default queue

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#92]
There is a need to preview summarized default queue content. 
How to do this now, when every Node has got it own default?

**Comment by rchac** [comment]
There is a default node for each CPU's top level HTB (so 16 default queues for a 16 core CPU). Technically a parent node defined in network.json, or even a generated node, is the leaf of that top level HTB for each CPU.

I'm not sure what command to use to see these packets in the default queue.

**Comment by dtaht** [comment]
Can we clarify and document how to get to this queue? It's very useful to be able to see where your topology is incorrect.

**Comment by rchac** [comment]
lqos_node_manager  now tracks all passing traffic, including traffic going to the default queue. Does that solve this sufficiently to close this issue?

**Comment by interduo** [comment]
How to check what packets goes into default queue?

**Comment by dtaht** [comment]
Good question. @rchac ?

**Comment by rchac** [comment]
You can see which IPs are being directed into the default queue by looking at http://SERVER:9123/unknown

**Comment by interduo** [comment]
@rchac thanks for this link...
