### ISSUE TITLE
Better binding 2 CPU cores for network traffic for one node (RX+TX) and generate less nodes

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#97]
Now we are using one CPU core for every one node for DL + UP.

Is it possible to generate half nodes - but use two cores (one for RX and another one for TX)?
It will better suits for big subscriber tariffs and I guess overall performance will be better.

**Comment by rchac** [comment]
Counterpoint: if we did this, half of CPU cores would be sitting around doing minimal processing since the upstream direction rarely uses as much bandwidth as the downstream - particularly as plans scale past 25 Mbps. Our network's current downstream/upstream usage ratio is 8:1 at the edge. 🤔

**Comment by interduo** [comment]
How much traffic can You archive per one subscriber?

**Comment by interduo** [comment]
> introduce our physical server soon.

use VM with passthrough like we use - its better to maintain (better to make failover/backup/move between hardware etc)

**Comment by interduo** [comment]
Two ideas resolving big plans on cpus with many not so performant cores:
Is it possible to use two cpu cores for every node/AP?
Is it possible to have one special node without assigned CPUCORE to TC MQ QUEUE?

I did some testing: if I remove filter transfers > 2gbps are working like a charm (those transfer get in default queue and use many cores instead of only one)

**Comment by interduo** [comment]
This testing machine will probbably not do more than 20gbps before:
![image](https://user-images.githubusercontent.com/17087236/190182525-f29c06c1-cd6b-4317-b0c8-ff1d0c6d9217.png)

**Comment by rchac** [comment]
> Is it possible to use two cpu cores for every node/AP?

We could probably do this in cases where CPU count is >= 8. My only hesitation is that it will complicate the code quite a bit.

> Is it possible to have one special node without assigned CPUCORE to TC MQ QUEUE?

Neat. I am not sure. There may be more clues [here](https://github.com/xdp-project/xdp-cpumap-tc/blob/master/src/tc_queue_mapping_kern.c).

> I did some testing: if I remove filter transfers > 2gbps are working like a charm (those transfer get in default queue and use many cores instead of only one)

Hm. Should we try out alternate IP filter methods, such as nftables maps? Perhaps that is the main bottleneck?

**Comment by interduo** [comment]
> We could probably do this in cases where CPU count is >= 8. My only hesitation is that it will complicate the code quite a bit.

Why >=8? and not >=4 ?

> Hm. Should we try out alternate IP filter methods, such as nftables maps? Perhaps that is the main bottleneck?

It looks like that... in our earlier envirnoment we used multi-level filtering it was very performant (we didnt used iptables for that only tc and u32). I saw that nftables supports maps now - it should be event better than multilevel filtering.

**Comment by interduo** [comment]
nftables supports atomic rule replacement (https://wiki.nftables.org/wiki-nftables/index.php/Atomic_rule_replacement) so maybe this would also resolve https://github.com/rchac/LibreQoS/issues/47.

**Comment by interduo** [comment]
Connected to:
https://github.com/xdp-project/xdp-cpumap-tc/issues/9

**Comment by rchac** [comment]
> nftables supports atomic rule replacement (https://wiki.nftables.org/wiki-nftables/index.php/Atomic_rule_replacement) so maybe this would also resolve #47.

So I tried and I cannot get nftables to classify and direct to the appropriate class, preumably because it has to be done via xdp-redirect when using xdp-cpumap-tc. Or I'm testing wrong. I will keep looking into this.

I'm currently reaching out to the handful of people associated with the XDP project who *might* have time to help with adding batch commands to xdp-cpumap-tc, as well as IPv6 prefix filtering.

**Comment by interduo** [comment]
> Question: do you have your NIC in pass-through mode or virtio virtual NIC?

Passthrough

**Comment by interduo** [comment]
Or using eBPF program like:
`$./xdp_redirect_cpu --progname xdp_cpu_map0 --dev eth0 --cpu 1` (it could be done like that from kern 5.9)

In that case we would need to generate some map for C++ program code and write a C++ program to filter packets to right CPU it could be even faster than using netstack with nftables.

**Comment by rchac** [comment]
@marsalans Do you use v1.1+? What's CPU load look like for you? Trying to decide if the additional complexity of two cores per node makes sense for most users.

**Comment by interduo** [comment]
When doing test try to use to set speeds on what one core will not handle (because of lack of performance) on one circuit.

I found something like that:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=1bca4e6b1863

Maybe this is the medicine for: https://github.com/rchac/LibreQoS/issues/99 and https://github.com/rchac/LibreQoS/issues/97 ?

**Comment by interduo** [comment]
> So I tried and I cannot get nftables to classify and direct to the appropriate class, preumably because it has to be done via xdp-redirect when using xdp-cpumap-tc. Or I'm testing wrong. I will keep looking into this.

How did You try? This is the bottleneck now.

**Comment by rchac** [comment]
First, I made sure the IP I wanted to use was not listed in ShapedDevices.csv (so it wouldnt have an XDP IP filter generated).

I tried using nftables to mimick iptables CLASSIFY to change the HTB-class id of IP traffic, based on this tip. https://github.com/xdp-project/xdp-cpumap-tc#dependencies-and-alternatives

Then created this file:
```
table ip filter {
    map iptoclass {
        type ipv4_addr : classid
        flags interval
        elements = { 100.64.68.1 : 2:80,
        }
    }
    chain iptoclass {
        meta priority none meta priority set ip daddr map @iptoclass counter packets 0 bytes 0
        meta priority none meta priority set ip saddr map @iptoclass counter packets 0 bytes 0
    }
}
```
And loaded using
```sudo nft -f nft.txt```

After noticing it wasn't working I deleted the filter sets:
```
sudo nft flush chain ip filter iptoclass
sudo nft delete chain ip filter iptoclass
sudo nft delete table ip filter
```

It's very possible I just did something wrong.

**Comment by interduo** [comment]
Looks like You use XDP so the packet don't pass normal kernel network stack way and it doesn't come to nft.

Well I think we could go in three ways now:
- drop using xdp (use nft maps for filtering, but use HTB MQ all all around to be resistant from HTB single-lock),
- use xdp-cpumap-tc from @thebracket after testing - he said that its working with **Trie**,
- wait for some update to xdp-cpumap-tc - I saw overview of LP conference papers 
(https://lpc.events/event/16/sessions/131/#20220912 - many things about eBPF)

**Comment by interduo** [comment]
If You allow to overwrite `queuesAvaiable` in `ispConfig.py` (https://github.com/rchac/LibreQoS/blob/main/v1.2/LibreQoS.py#L81) I would test how LQS is behaving when we assign 2cores to queue - its easy to configure, just change smp_affinity on the fly.

**Comment by rchac** [comment]
Gotcha. Here is [a branch to test that](https://github.com/rchac/LibreQoS/blob/setqueues/v1.2/).

**Comment by interduo** [comment]
```
root@dev-libreqos:~/LibreQoS/v1.2# ./LibreQoS.py
refreshShapers starting at 27/09/2022 11:16:02
Not first time run since system boot.
network.json passed validation
ShapedDevices.csv passed validation
Backed up good config as lastGoodConfig.csv and lastGoodConfig.json
Traceback (most recent call last):
  File "/root/LibreQoS/v1.2/./LibreQoS.py", line 911, in <module>
    refreshShapers()
  File "/root/LibreQoS/v1.2/./LibreQoS.py", line 421, in refreshShapers
    queuesAvailable = findQueuesAvailable()
  File "/root/LibreQoS/v1.2/./LibreQoS.py", line 91, in findQueuesAvailable
    print("queuesAvailable set to:\t" + str(queuesAvailable))
```

**Comment by interduo** [comment]
Maybe default value could be:
`queuesAvailable = 0` whitch means autodetection - if the variable is set to some smallinteger ommit autodetection.

**Comment by rchac** [comment]
Ok. Changed to queuesAvailableOverride. if set to 0, proceeds normally. If set to any other integer, that overrides queuesAvailable.

Please make sure to have queuesAvailableOverride = 0 in your [ispConfig.py](https://github.com/rchac/LibreQoS/blob/setqueues/v1.2/ispConfig.example.py)

https://github.com/rchac/LibreQoS/blob/setqueues/v1.2/

**Comment by interduo** [comment]
Ok - no errors, generating all the nodes and rules in order/form for queues like we would like to have. 

If You do the merge, the issue could be closed.

**Comment by interduo** [comment]
Ok - I can set the right affinity by hand - but I am thinking how to make this happen by script magic.
I suggest to rise an warning when the QueuesCount is bigger than CPU cores.

Case 1: (this is now)
1 core for 1 queue, 8 queues, 8 cores 

Case 2: (every one queue should use two core exclusiveles)
2 cores for 1 queue, 4 queues, 8 cores total
*1-->cores 0-1,
*2-->cores 2-3,
*3-->cores 4-5,
*4-->cores 6-7,

Case 3: (every one queue should use two cores NOT exclusiveles)
2 cores for 1 queue, 16 queues, 8 cores total
*1-->cores 0,1
*2-->cores 2,3
*3-->cores 4,5
*3-->cores 4,5
*3-->cores 4,5
*3-->cores 4,5
*3-->cores 4,5

**Comment by rchac** [comment]
Does this help? https://github.com/rchac/LibreQoS/commit/bf5ced45a813a4d294319340de310ea974dcede4

**Comment by interduo** [comment]
Ok - I can set the right affinity by hand - but I am thinking how to make this happen by script magic.

Firstly I suggest to rise an warning when the QueuesCount is bigger than avaiable CPU cores.

Case 1: (this is now)
1 core for 1 queue, 8 queues, 8 cores 

Case 2: (every one queue should use two core exclusiveles)
2 cores for 1 queue, 4 queues, 8 cores total
```
*1-->cores 0-1,
*2-->cores 2-3,
*3-->cores 4-5,
*4-->cores 6-7,
```

Case 3: (every one queue should use two cores but NOT exclusiveles)
2 cores for 1 queue, 8 queues, 8 cores total
```
*1-->cores 0,1
*2-->cores 2,3
*3-->cores 4,5
*4-->cores 6,7
*5-->cores 0,1
*6-->cores 2,3
*7-->cores 4,5
*8-->cores 6,7
```

**Comment by interduo** [comment]
This branch could be meged now in my opinion. This function is great even if we don't change the smp_affinity.

**Comment by dtaht** [comment]
Aside from a need to document this a bit better, closing...
